
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Ckfiumi :: come funziona? </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa," />
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..." />
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0=" />
<link href="http://www.ckfiumi.net/css/defaults.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://www.ckfiumi.net/js/all-1.js"></script>
<script type="text/javascript">
if(top.location != location) {
   top.location.href = document.location.href;
}
</script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
	<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
	<div id="mainFront">
	  	<img id="a" src="http://www.ckfiumi.net/img/header/21.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
	</div>
    <div id="containerMenu"><div
   		 id="menu_left"><img src="http://www.ckfiumi.net/img/sfondo_barra_sx.gif"  alt="" /></div><div
		  id="menu_right"><img src="http://www.ckfiumi.net/img/sfondo_barra_dx.gif"  alt="" /></div><div
		  id="menu_orizz">
			<a  class="menu" href="/">Home</a> |
			<a  class="menu" href="/fiume.phtml">Fiumi</a> |
			<a  class="menu" href="/news/calendario.phtml">Appuntamenti</a> |
			<a  class="menu" href="/mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
			<a  class="menu_selected_U" href="http://forum.ckfiumi.net">Forums CKI</a> |
			<a  class="menu" href="/racconti.phtml">Vita di Fiume</a> |
			<a  class="menu" href="/contatto.phtml">Scrivici</a> |
			<a  class="menu" href="/login.phtml">Login</a> |
		</div>
	</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->	



	<!-- BEGIN MAIN AREA -->
	<div id="main">
		<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
      	<tr>
        	<td class="sxCol">
			<div id="elCont">
				<div id="elCont_left" class="z_listaHelp"></div><div
		  		id="elCont_right">Piccola guida di auto salvamento per il sito</div>
			</div>
			<div id="sottoElCont">	
				<!-- BEGIN  CONTENTS -->
				<p> 
Brevi istruzioni per gli utenti.<br/>
1. <a href="#ricerca">Come trovare la descrizione di un tratto di fiume con tre metodi diversi.</a><br/>
2. <a href="#editori">Come inserire o aggiornare i  fiumi ed i loro tratti.</a><br/>
 <br/><br/>
<span class="label_s"><a name="ricerca">1. Come trovare la descrizione di un tratto di fiume</a></span><br/>
<b>Metodo #1</b> - In ordine alfabetico:<br/>
-Selezionare <a href="/fiume.phtml">lista fiumi</a><br/>
-selezionare la nazione con la finestra a discesa<br/>
-cliccare su una lettera dell'alfabeto. Sotto appariranno i nomi dei fiumi<br/>
della nazione scelta presenti nel database e che iniziano con la lettera<br/>
selezionata.<br/>
-Cliccare sul nome del fiume, appariranno i report che sono stati inseriti<br/>
dagli editori;<br/>
-Selezionare un report per consultare le informazioni.<br/>
STAMPA: per stampare la pagina selezionare il link che si trova nella<br/>
pagina del report in basso a destra, con vicino l'icona (immagine icona) della stampante.<br/>
<br/>
<br/>
<b>Metodo #2</b> - Con la pagina delle ricerche:<br/>
- Selezionare <a href="/ricerca.phtml">ricerca fiumi</a><br/>
- compilare i campi che interessano e poi premere il tasto "cerca".<br/>
In basso a sinistra apparranno i fiumi che soddisfano le caratteristiche<br/>
richieste. Se non appare nulla provate a cancellare qualcuno dei dati<br/>
inseriti nella ricerca.<br/>
- selezionare un fiume e poi ripetere le operazioni già descritte nel<br/>
"metodo uno".<br/>
<br/>
<br/> 
<b>Metodo #3</b> - Con la mappa:<br/>
- Con il cursore passare sulla <a href="/fiume.phtml">mappa</a> e selezionare un zona geografica<br/>
cliccando ci sopra, appariranno i fiumi inseriti;<br/>
- Selezionare un fiume e poi ripetere le operazioni già descritte nel<br/>
"metodo uno"<br/>
</p>
<br/>
<hr/>
<br/>

<p>
<span class="label_s"><a name="editori">2. Come inserire o aggiornare un fiume</a></span> - Tutti possono inserire un nuovo fiume oppure modificare e 
completare la descrizione di un tratto di fiume  gi&agrave; presente. <br/><br/>
L'unica cosa richiesta &egrave; la <a href="/registra.phtml">registrazione</a> come editore da parte tua. <br/>
<br/>
Previa registrazione, chiunque pu&ograve; sottoporre ai moderatori del sito un report ex-novo  <br/>
oppure un report aggiornato e modificato sulla base di uno gi&agrave; esistente. I moderatori, <br/>
secondo loro discrezione e/o esperienza, potranno decidere se pubblicare o meno le eventuali modifiche, 
integrazioni o aggiunte proposte dall' editore. <br/>
<br/>
Ci teniamo a sottolineare che i tratti di fiume qui riportati non appartengono a nessuno in particolare. <br/>
<b>La prima persona che inserisce un report per un tratto di fiume non ne diventa l' autore esclusivo</b>. 

Speriamo in questo modo di riuscire a  favorire il lavoro della comunit&agrave; intera ad un progetto di cui tutti potranno  
beneficiare fornendo ed ottenendo informazioni sempre aggiornate. <br/>
</p>

<br/><hr/><br/>
<p>
Se qualcosa non ti è chiaro puoi contattarci utilizzando l'apposito form che<br/>
trovi selezionando <a href="/contatto.phtml">scrivici</a>.<br/>
<br/>
<br/>
<br/>
</p>

				<!-- END  CONTENTS -->
			</div>
			</td>
        	<td class="dxCol">
				<!-- INIZIO MENU DX -->
			<div id="menudx">
			<ul>
				<li class="menu"><a href="/login.phtml">Login</a></li>
				<li class="menu"><a href="/registra.phtml">Registrati</a></li>
				<li class="menu"><a href="/recupera.phtml">Recupera Password</a></li>
				<li class="submenu_selected_U"><a href="/help.phtml">Come Funziona</a></li>
				<li class="menu"><a href="/madeby.phtml">Chi siamo</a></li>
				<li class="menu"><a href="/show.phtml">Lista Editori</a></li>
			</ul>
			</div>
			<div class="textWel">
		 	 <a href="/registra.phtml">Diventa anche tu un editore!</a>
		  	</div>	
			<div class="textWel">
			<p>TI RICORDIAMO CHE:<br/>
			1- I fiumi vanno discesi con  attrezzature e abbigliamento  adatto al tipo di percorso 
			affrontato.<br/> 
			2- Per discendere i fiumi bisogna frequentare dei corsi di canoa tenuti da 
			personale qualificato.<br/> 
			3- I principianti durante le discese devono essere affiancati e consigliati 
			da guide esperte.<br/>
			4- Una discesa non si effettua mai in solitaria, il numero minimo dei partecipanti può variare 
			a seconda della preparazione dei canoisti e delle difficoltà che si possono incontrare.
			</p>
			</div>
<!-- FINE MENU DX -->		

			</td>
      	</tr>
    	</table>
	</div>
	<!-- END MAIN AREA -->
		<!-- INIZIO FOOTER -->
		<div id="footer">
		      <p><a href="/">home</a> &#8226;  
			  <a href="/fiume.phtml">fiumi</a> &#8226; 
			  <a href="/ricerca.phtml">ricerca fiumi</a> &#8226;
			  <a href="/help.phtml">come funziona</a>  &#8226;
			  <a href="/gradi.phtml">I gradi WW</a> &#8226; 
			  <a href="/contatto.phtml">scrivici</a> &#8226; 
			  <a href="/profilo.phtml/dani">webmaster</a>  
			  </p>
				<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o 
			pubblicazione  anche parziale per fini commerciali<br/>
			</p>
	<p class="loghi"><a href="/redirect.phtml?target=firaft" rel="nofollow"><img src="/img/sponsor/firaft.jpg" style="border:0px" alt="FIRAFT"/></a>
	&nbsp;<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	</p>
		</div>
	</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-666569-2";
urchinTracker();
</script>
</body>
</html>




