<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Ckfiumi :: Chi siamo </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa," />
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..." />
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0=" />
<link href="/css/defaults.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/dyna.js"></script>
<script type="text/javascript" src="/js/p_switch.js"></script>	
<script type="text/javascript" src="/js/net/ckfiumi/prototype.js"></script>
<script type="text/javascript" src="/js/net/ckfiumi/text-utils.js"></script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
	<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
	<div id="mainFront">
	  	<img id="a" src="/img/header/14.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
	</div>
    <div id="containerMenu"><div
   		 id="menu_left"><img src="/img/sfondo_barra_sx.gif"  alt="" /></div><div
		  id="menu_right"><img src="/img/sfondo_barra_dx.gif"  alt="" /></div><div
		  id="menu_orizz">
			<a  class="menu" href="/">Home</a> |
			<a  class="menu" href="/fiume.phtml">Fiumi</a> |
			<a  class="menu" href="/news/calendario.phtml">Appuntamenti</a> |
			<a  class="menu" href="/mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
			<a  class="menu_selected_U" href="http://forum.ckfiumi.net">Forums CKI</a> |
			<a  class="menu" href="/racconti.phtml">Vita di Fiume</a> |
			<a  class="menu" href="/contatto.phtml">Scrivici</a> |
			<a  class="menu" href="/login.phtml">Login</a> |
		</div>
	</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->	



	<!-- BEGIN MAIN AREA -->
	<div id="main">
		<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
      	<tr>
        	<td class="sxCol">
			<div id="elCont">
				<div id="elCont_left" class="z_ckfTeam"></div><div
		  		id="elCont_right">Il team di CKFiumi</div>
			</div>
			<div id="sottoElCont">	
				<!-- BEGIN  CONTENTS -->
				<script type="text/javascript">
function addams_show(img,addams,ps){
	img.src="/img/" + addams + "noi_" + ps + ".jpg";
}
</script>
<table cellspacing="2" cellpadding="1" border="0px" width="545px">
<tr>
	<td class="madeby"><img src="/img/noi_dani.jpg" style="border:0px;width:100px" onmouseover="addams_show(this,'addams_','dani')" onmouseout="addams_show(this,'','dani')"/></td>
	<td class="madeby"><span class="nome">Daniela Mariaschi</span>  è la nostra "Fantomatica Webmaster". <br/>
	Ha curato la parte di Programmazione e Database.<br/>
	<br/>
	Id Skype: <a href="callto://damarat">Damarat</a> </td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_flavio.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','flavio')" onmouseout="addams_show(this,'','flavio')"/></td>
	<td class="madeby"><span class="nome">Flavio Ciarrocchi</span> (CKI) è il nostro Project Manager &amp; Public Relation Man. In effetti ... e chi non lo conosce? <br/>
	<br/>
	Id Skype: <a href="callto://flavio.ciarrocchi">flavio.ciarrocchi</a></td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_ale.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','ale')" onmouseout="addams_show(this,'','ale')"/></td>
	<td class="madeby"><span class="nome">Ale Mai</span> è il nostro progettista grafico. Vive di pane e css, non parlategli di table per carità!!<br/>
	<br/>
	Id Skype: <a href="callto://Alex%20'RedEye'%20Mai">Alex 'Red Eye' Mai</a>
	</td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_stefano.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','stefano')" onmouseout="addams_show(this,'','stefano')"/></td>
	<td class="madeby"><span class="nome">Stefano Caprile</span> (Canoa Club Novara) è il nostro Uomo dei Report per antonomasia.<br/><br/>
	Vedi i reports sul Sesia per capire :)</td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_marco.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','marco')" onmouseout="addams_show(this,'','marco')"/></td>
	<td class="madeby"><span class="nome">Marco Lascialfari</span> (Circolo Sportivo Marina di Candeli ) è il nostro Uomo Test Instancabile.<br/> Ha pensato ai test più strani e martellanti per tutto il periodo di sviluppo.
	<br/>E' parte anche del nostro "Ufficio Stampa: articoli".
	</td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_nunzio.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','nunzio')" onmouseout="addams_show(this,'','nunzio')"/></td>
	<td class="madeby"><span class="nome">Nunzio Mortelliti</span> (Canoa Fluviale Martesana) è l' altro nostro uomo dei Reports in attesa di connessione flat 
	(ma sì è skypezzato anche lui alla fine) <br/>
	<br/>
	Id Skype: <a href="callto://incredibilenunz">incredibilenunz</a>
	</td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_francesco.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','francesco')" onmouseout="addams_show(this,'','francesco')"/></td>
	<td class="madeby"><span class="nome">Francesco Elia</span> splendido aiuto factotum. Per quel che c'è bisogno lui provvede. Davvero molto costruttivo.
	<br/>E' parte anche del nostro "Ufficio Stampa: articoli".
		<br/><br/>
		Id Skype: <a href="callto://francesco.elia">francesco.elia</a>
	</td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_philo.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','philo')" onmouseout="addams_show(this,'','philo')"/></td>
	<td class="madeby"><span class="nome">Philippe Devanneaux</span> (Canoa Club Asola) è il nostro secondo grafico nonchè fotografo. Dalla sua canoa cerca di cogliere l'attimo sfuggente!<br/>
	(Le foto in alto sono  sue, vi siete riconosciuti?)<br/>
	<br/>
	Id Skype: <a href="callto://phildev999">phildev999</a>
	</td>
</tr>
<tr>
	<td class="madeby"><img src="/img/noi_massimo.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','massimo')" onmouseout="addams_show(this,'','massimo')"/></td>
	<td class="madeby"><span class="nome">Massimo Delledonne</span> ha intrapreso la dura crociata per ottenere la lettura dei livelli idrometrici delle ARPA.<br/>
	Si è guadagnato sul campo l' assegnazione al nostro "Ufficio Stampa: relazioni con la pubblica amministrazione" !
	<br/><br/>
	Id Skype: <a href="callto://massimo.delledonne">massimo.delledonne</a>
	</td>
</tr>
<!--<tr>
	<td class="madeby"><img src="/img/noi_daniele.jpg" style="border:0px;width:100px"  onmouseover="addams_show(this,'addams_','daniele')" onmouseout="addams_show(this,'','daniele')"/></td>
	<td class="madeby"><span class="nome">Daniele Vaccari</span> la nostra new entry. Daniele è l'uomo dei video, ci ha permesso di
	vedere molti momenti delle gare d' alto corso di quest' anno. Lo ringraziamo anche per lo spazio messo a disposizione sul suo server.
	<br/><br/>
	</td>
</tr>
-->
</table>
<br/><br/>
<div>Cammin facendo hanno contribuito inoltre :</div> 
<div style="margin-left:10px;padding:8px">Andrea Gangemi (Tester)<br/>
Luigi Giardina (Tester)<br/>
Frederik Beccaro (Uomo report)<br/>
Valerio Villa<br/>
Fabrizio Cappa<br/>
Beppe Puddu<br/>
Francesco Pamio<br/>
Daniele Vaccari<br/>
</div>

				<!-- END  CONTENTS -->
			</div>
			</td>
        	<td class="dxCol">
				<!-- INIZIO MENU DX -->
			<div id="menudx">
			<ul>
				<li class="menu"><a href="/login.phtml">Login</a></li>
				<li class="menu"><a href="/registra.phtml">Registrati</a></li>
				<li class="menu"><a href="/recupera.phtml">Recupera Password</a></li>
				<li class="menu"><a href="/help.phtml">Come Funziona</a></li>
				<li class="submenu_selected_U"><a href="/madeby.phtml">Chi siamo</a></li>
				<li class="menu"><a href="/show.phtml">Lista Editori</a></li>
			</ul>
			</div>
			<div class="textWel">
		 	 <a href="/registra.phtml">Diventa anche tu un editore!</a>
		  	</div>	
			<div class="textWel">
			<p>TI RICORDIAMO CHE:<br/>
			1- I fiumi vanno discesi con  attrezzature e abbigliamento  adatto al tipo di percorso 
			affrontato.<br/> 
			2- Per discendere i fiumi bisogna frequentare dei corsi di canoa tenuti da 
			personale qualificato.<br/> 
			3- I principianti durante le discese devono essere affiancati e consigliati 
			da guide esperte.<br/>
			4- Una discesa non si effettua mai in solitaria, il numero minimo dei partecipanti può variare 
			a seconda della preparazione dei canoisti e delle difficoltà che si possono incontrare.
			</p>
			</div>
<!-- FINE MENU DX -->		

			</td>
      	</tr>
    	</table>
	</div>
	<!-- END MAIN AREA -->
		<!-- INIZIO FOOTER -->
		<div id="footer">
		      <p><a href="/">home</a> &#8226;  
			  <a href="/fiume.phtml">fiumi</a> &#8226; 
			  <a href="/ricerca.phtml">ricerca fiumi</a> &#8226;
			  <a href="/help.phtml">come funziona</a>  &#8226;
			  <a href="/gradi.phtml">I gradi WW</a> &#8226; 
			  <a href="/contatto.phtml">scrivici</a> &#8226; 
			  <a href="/profilo.phtml/dani">webmaster</a>  
			  </p>
				<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o 
			pubblicazione  anche parziale per fini commerciali<br/>
			</p>
	<p class="loghi"><a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	</p>
		</div>
	</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-666569-2";
urchinTracker();
</script>
</body>
</html>


