










<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Ckfiumi :: La sicurezza in fiume </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa," />
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..." />
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0=" />
<link href="http://www.ckfiumi.net/css/defaults.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://www.ckfiumi.net/js/all-1.js"></script>
<script type="text/javascript">
if(top.location != location) {
   top.location.href = document.location.href;
}
</script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
	<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
	<div id="mainFront">
	  	<img id="a" src="http://www.ckfiumi.net/img/header/11.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
	</div>
    <div id="containerMenu"><div
   		 id="menu_left"><img src="http://www.ckfiumi.net/img/sfondo_barra_sx.gif"  alt="" /></div><div
		  id="menu_right"><img src="http://www.ckfiumi.net/img/sfondo_barra_dx.gif"  alt="" /></div><div
		  id="menu_orizz">
			<a  class="menu" href="/">Home</a> |
			<a  class="menu_selected_U" href="/fiume.phtml">Fiumi</a> |
			<a  class="menu" href="/news/calendario.phtml">Appuntamenti</a> |
			<a  class="menu" href="/mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
			<a  class="menu" href="http://forum.ckfiumi.net">Forums CKI</a> |
			<a  class="menu" href="/racconti.phtml">Vita di Fiume</a> |
			<a  class="menu" href="/contatto.phtml">Scrivici</a> |
			<a  class="menu" href="/login.phtml">Login</a> |
		</div>
	</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->	



	<!-- BEGIN MAIN AREA -->
	<div id="main">
		<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
      	<tr>
        	<td class="sxCol">
			<div id="elCont">
				<div id="elCont_left" class="z_newso"></div><div
		  		id="elCont_right">I Segnali in Fiume</div>
			</div>
			<div id="sottoElCont">	
				<!-- BEGIN  CONTENTS -->
				<div style="font-weight:bold;">
A cura delle Guide Fluviali FICT: la nuova segnaletica fluviale usata dai professionisti.
</div>
<div style="padding-top:5px;text-align:justify">
In fiume, capita spesso di dovere comunicare con i propri compagni di discesa.<br/> 
Le segnalazioni visive sono il mezzo più veloce ed efficace per farsi capire
quando ci si trova in ricognizione su sponde diverse ad esempio, oppure quando 
fra i compagni di discesa vi sono persone straniere, o ogni volta che il rumore della corrente
sovrasta il suono delle nostre parole.<br/><br/>
Facciamo attenzione però perchè, a volte, un particolare gesto per una persona può 
avere significati diversi rispetto a quelli che intendiamo noi (capita spesso con stranieri), 
è quindi buona norma, prima della discesa, verificare che tutti i partecipanti capiscano ed usino
una segnalatica comune. 
<br/><br/>
Riportiamo le foto della nuova segnalatica fluviale usata dai professionisti
e presentata al corso di aggiornamento dei Tecnici <a href="http://www.canoa.org">FICT</a> sul fiume Vara (anno 2006), ringraziando della collaborazione
le Guide Fluviali <a href="http://www.canoa.org">FICT</a>.
</div>

<div class="sgn_container">
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7805.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare al Centro<br/>(stay in the middle of the current) </div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7807.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare a Centro Destra<br/>(middle right) </div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7809.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare a Destra <br/>(stay on the right)</div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7811.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare all' Estrema Destra<br/>(farthest-extreme right) </div>
<!-- SX -->
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7814.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare a Centro Sinistra<br/>(middle left) </div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7816.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare a Sinistra <br/>(stay on the left) </div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7818.jpg" alt="" />
	</div>
	<div class="sgn_testo">passare all' Estrema Sinistra<br/>(farthest-extreme left) </div>

	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7822.jpg" alt="" />
	</div>
	<div class="sgn_testo">Roccia <br/>(rock)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7823.jpg" alt="" />
	</div>
	<div class="sgn_testo">Nicchia o Sifone<br/>(undercut or syphon) </div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7829.jpg" alt="" />
	</div>
	<div class="sgn_testo">Rullo<br/>(stopper) </div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7825.jpg" alt="tronco" /><img src="/img/segnali/Dsc_7826.jpg" alt="tronco" />
	</div>
	<div class="sgn_testo">Tronco<br/>(tree-log) </div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7831.jpg" alt="" />
	</div>
	<div class="sgn_testo">Morta<br/>(eddy-breakout)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7835.jpg" alt="" />
	</div>
	<div class="sgn_testo">Passare sulla lingua d'acqua<br/>(pass on the water tongue)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7838.jpg" alt="" />
	</div>
	<div class="sgn_testo">Passare sul naso (roccia su cui passa acqua)<br/>boof on the rock</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7840.jpg" alt="" />
	</div>
	<div class="sgn_testo">Salto<br/>(drop-fall) </div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7841.jpg" alt="" />
	</div>
	<div class="sgn_testo">C'è un sasso sotto il salto<br/>(rock under the drop-fall)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7829.jpg" alt="" /><img src="/img/segnali/Dsc_7844.jpg" alt="" />
	</div>
	<div class="sgn_testo">Rullo  che TIENE !!<br/>(HOLDING hole-stopper!!)</div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7845.jpg" alt="" />
	</div>
	<div class="sgn_testo">Pagaiare deciso !!!<br/>(paddle hard)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7847.jpg" alt="" />
	</div>
	<div class="sgn_testo">Boof</div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7850.jpg" alt="" />
	</div>
	<div class="sgn_testo">Ricognizione<br/>(scouting)</div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7853.jpg" alt="" />
	</div>
	<div class="sgn_testo">Impraticabile<br/>(unnavigable) </div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7854.jpg" alt="" /><img src="/img/segnali/Dsc_7855.jpg" alt="" />
	</div>
	<div class="sgn_testo">Trasbordare<br/>(portage)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7859.jpg" alt="" />
	</div>
	<div class="sgn_testo">Energico, Potente (il braccio si muove in su e già)<br/>(powerful)</div>

	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7862.jpg" alt="" />
	</div>
	<div class="sgn_testo">OK </div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7863.jpg" alt="" /><img src="/img/segnali/Dsc_7864.jpg" alt="" />
	</div>
	<div class="sgn_testo">Tagliare da Sx a Dx (orografica)<br/>(cut from left to right)</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7867.jpg" alt="" /><img src="/img/segnali/Dsc_7868.jpg" alt="" />
	</div>
	<div class="sgn_testo">Tagliare da Dx a Sx (orografica)<br/>(cut from right to left)</div>
	
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7872.jpg" alt="" />
	</div>
	<div class="sgn_testo">Corda <br/> (throw-line, rope)</div>
		<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7873.jpg" alt="" />
	</div>
	<div class="sgn_testo">STOP !</div>
	<div class="sgn_foto">
		<img src="/img/segnali/Dsc_7875.jpg" alt="" />
	</div>
	<div class="sgn_testo">Avanti !<br/>GO</div>

<br/>
<div>
Si ringraziano per le foto: <br/>
- Gigi Rizzitelli (Guida Fluviale Istruttore FICT)<br/>
- Stefano Stanga (Guida Fluviale FICT)
<br/>
</div>	
	
	
</div>



 


				<!-- END  CONTENTS -->
			</div>
			</td>
        	<td class="dxCol">
				<!-- INIZIO MENU DX -->
			<div id="menudx">
			<ul>
				<li class="menu"><a href="/fiume.phtml">Fiumi</a></li>
				<li class="menu" ><a href="/idro/">Idrometri online</a></li>
				<li class="menu" ><a href="/ricerca.phtml">Ricerca Fiume</a></li>
				<li class="menu"><a href="/gradi.phtml">I gradi W W</a></li>
				<li class="submenu_selected_U"><a href="/segnali.phtml">I Segnali in fiume</a></li>
			</ul>
			</div>
			<div class="textWel">
		 	 <a href="/registra.phtml">Diventa anche tu un editore!</a>
		  	</div>	
			<div class="usrListAlfabetica">
			<fieldset><legend>fiumi ordine alfabetico</legend>
				<form id="cercaFiume" method="get" action="/fiume.phtml">
	<div style="width:170px;font-size: 9px;text-align:right;">
		<input type="hidden" value="{ListaAlfabetica::lettera}" name="letter"/>
		<select name="nazione" style="font-size: 9px;" onchange="document.getElementById('cercaFiume').submit()">
			
				<option value="IT"  selected="selected">Italia</option>
			
				<option value="A" >Austria</option>
			
				<option value="BAL" >Balcani</option>
			
				<option value="FR" >Francia</option>
			
				<option value="GR" >Grecia</option>
			
				<option value="NOR" >Norvegia</option>
			
				<option value="SLO" >Slovenia</option>
			
				<option value="ES" >Spagna</option>
			
				<option value="CH" >Svizzera</option>
			
		</select>
	</div> 
	<div style="width:170px;font-size: 9px;padding-left:2px;padding-top:2px;padding-rigth:2px;padding-bottom:0px;">
<!-- inizio listaAlfabetica -->
	<table border="0" style="font-size:14px;font-weight:lighter;"  cellpadding="0" cellspacing="0">
 
    <tr>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/A"><b>A</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/B"><b>B</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/C"><b>C</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/D"><b>D</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/E"><b>E</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/F"><b>F</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/G"><b>G</b></a></td>
		<td > &nbsp; </td>

        
    </tr>
 
    <tr>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/H"><b>H</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/I"><b>I</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/J"><b>J</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/K"><b>K</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/L"><b>L</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/M"><b>M</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/N"><b>N</b></a></td>
		<td > &nbsp; </td>

        
    </tr>
 
    <tr>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/O"><b>O</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/P"><b>P</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/Q"><b>Q</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/R"><b>R</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/S"><b>S</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/T"><b>T</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/U"><b>U</b></a></td>
		<td > &nbsp; </td>

        
    </tr>
 
    <tr>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/V"><b>V</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/W"><b>W</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/X"><b>X</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/Y"><b>Y</b></a></td>
		<td > &nbsp; </td>

        <td class="listaAlfabetica"><a class="" href="/fiume.phtml/letter/Z"><b>Z</b></a></td>
		<td > &nbsp; </td>

        
    </tr>
	
</table>

<br />
<!-- fine listaAlfabetica -->
	</div>
	</form>
	
	



			</fieldset>
			<fieldset><legend>fiumi per regione</legend>
			<form id="FiumiPerRegioni" method="get" action="/fiume.phtml">
	<div style="width:170px;font-size: 9px;text-align:right;">
		<select name="regione" style="font-size: 9px;" onchange="document.getElementById('FiumiPerRegioni').submit()">
			<option value="">-- seleziona --</option>
			
				<option value="1" >Abruzzo</option>
			
				<option value="2" >Basilicata</option>
			
				<option value="3" >Calabria</option>
			
				<option value="4" >Campania</option>
			
				<option value="5" >Emilia Romagna</option>
			
				<option value="6" >Friuli Venezia Giulia</option>
			
				<option value="7" >Lazio</option>
			
				<option value="8" >Liguria</option>
			
				<option value="9" >Lombardia</option>
			
				<option value="10" >Marche</option>
			
				<option value="11" >Molise</option>
			
				<option value="12" >Piemonte</option>
			
				<option value="13" >Puglia</option>
			
				<option value="14" >Sardegna</option>
			
				<option value="15" >Sicilia</option>
			
				<option value="16" >Toscana</option>
			
				<option value="17" >Trentino Alto Adige</option>
			
				<option value="18" >Umbria</option>
			
				<option value="19" >Val d'Aosta</option>
			
				<option value="20" >Veneto</option>
			
		</select>
	</div> 
</form>
	
	

			</fieldset>
			</div>
			<div class="textWel">
			<p>TI RICORDIAMO CHE:<br/>
			1- I fiumi vanno discesi con  attrezzature e abbigliamento  adatto al tipo di percorso 
			affrontato.<br/> 
			2- Per discendere i fiumi bisogna frequentare dei corsi di canoa tenuti da 
			personale qualificato.<br/> 
			3- I principianti durante le discese devono essere affiancati e consigliati 
			da guide esperte.<br/>
			4- Una discesa non si effettua mai in solitaria, il numero minimo dei partecipanti può variare 
			a seconda della preparazione dei canoisti e delle difficoltà che si possono incontrare.
			</p>
			</div>

<!-- FINE MENU DX -->		

			</td>
      	</tr>
    	</table>
	</div>
	<!-- END MAIN AREA -->
		<!-- INIZIO FOOTER -->
		<div id="footer">
		      <p><a href="/">home</a> &#8226;  
			  <a href="/fiume.phtml">fiumi</a> &#8226; 
			  <a href="/ricerca.phtml">ricerca fiumi</a> &#8226;
			  <a href="/help.phtml">come funziona</a>  &#8226;
			  <a href="/gradi.phtml">I gradi WW</a> &#8226; 
			  <a href="/contatto.phtml">scrivici</a> &#8226; 
			  <a href="/profilo.phtml/dani">webmaster</a>  
			  </p>
				<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o 
			pubblicazione  anche parziale per fini commerciali<br/>
			</p>
	<p class="loghi"><a href="/redirect.phtml?target=firaft" rel="nofollow"><img src="/img/sponsor/firaft.jpg" style="border:0px" alt="FIRAFT"/></a>
	&nbsp;<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	</p>
		</div>
	</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-666569-2";
urchinTracker();
</script>
</body>
</html>




