<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Ckfiumi :: sostenitori Ckfiumi </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa," />
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..." />
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0=" />
<link href="http://www.ckfiumi.net/css/defaults.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://www.ckfiumi.net/js/all-1.js"></script>
<script type="text/javascript">
if(top.location != location) {
   top.location.href = document.location.href;
}
</script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
	<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
	<div id="mainFront">
	  	<img id="a" src="http://www.ckfiumi.net/img/header/22.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
	</div>
    <div id="containerMenu"><div
   		 id="menu_left"><img src="http://www.ckfiumi.net/img/sfondo_barra_sx.gif"  alt="" /></div><div
		  id="menu_right"><img src="http://www.ckfiumi.net/img/sfondo_barra_dx.gif"  alt="" /></div><div
		  id="menu_orizz">
			<a  class="menu" href="/">Home</a> |
			<a  class="menu" href="/fiume.phtml">Fiumi</a> |
			<a  class="menu" href="/news/calendario.phtml">Appuntamenti</a> |
			<a  class="menu" href="/mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
			<a  class="menu_selected_U" href="http://forum.ckfiumi.net">Forums CKI</a> |
			<a  class="menu" href="/racconti.phtml">Vita di Fiume</a> |
			<a  class="menu" href="/contatto.phtml">Scrivici</a> |
			<a  class="menu" href="/login.phtml">Login</a> |
		</div>
	</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->	



	<!-- BEGIN MAIN AREA -->
	<div id="main">
		<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
      	<tr>
        	<td class="sxCol">
			<div id="elCont">
				<div id="elCont_left" class="z_ckfTeam"></div><div
		  		id="elCont_right">Sostenitori ed Amici di CKfiumi/CKI</div>
			</div>
			<div id="sottoElCont">	
				<!-- BEGIN  CONTENTS -->
				<script language="javascript">
		var currentTabId ='2012';
		function enableTab (id)	{
			if (id == currentTabId) {
				return;
			}
			obj = document.getElementById ('panel' + id);
			obj.className = "visiblePanel";
			obj = document.getElementById ('tab' + id);
			obj.className = "visibleTab";
			obj = document.getElementById ('panel' + currentTabId);
			obj.className = "hiddenPanel";
			obj = document.getElementById ('tab' + currentTabId);
			obj.className = "hiddenTab";
			currentTabId = id;
		}
</script>
<div>inviaci la tua foto a : <img src="/img/mail_foto.jpg" alt="foto" title="foto"/> </div>
<div class="tab_container" style="border:0">
	<div style="margin-top:2px" >
		<div id="tab2012" style="float:left" class="visibleTab" onClick="enableTab('2012')"><span class="simulate_href">2012</span></div>
		<div id="tab2011" style="float:left" class="hiddenTab" onClick="enableTab('2011')"><span class="simulate_href">2011</span></div>
	</div>
	
	<div id="panel2012" class="visiblePanel">	
		<ul class="resourceList" >
		  
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameA" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">lucaswim</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/luca_perondi.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/luca_perondi.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Luca Perondi</strong>
				           </dt>
				           <dd>
				            Trezzo Kayak
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameA" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">fede</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <img src="/img/logo_bn.jpg">
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Federico Ricci</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameB" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">Pec</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/marco_pec.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/marco_pec.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Marco Pecchio</strong>
				           </dt>
				           <dd>
				            Pagaia Rossa 
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameB" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/index.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/index.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Henry Principe</strong>
				           </dt>
				           <dd>
				            Canoa Club Brescia 
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameC" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/giuliano_bruschi.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/giuliano_bruschi.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Giuliano Bruschi</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameC" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/paolo_costantini.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/paolo_costantini.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Paolo Costantini</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uNameC" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/milena_velati.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/milena_velati.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Milena Velati</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		</ul>
	</div>
	

	<div id="panel2011" class="hiddenPanel">	
		<ul class="resourceList" >
		  
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.gravitazero.info/">www.gravitazero.info/</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.gravitazero.info/" target="_blank"><img border="0" src="/rep/editori/gravita_zero.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Gravità Zero </strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.acquaviva.org  ">www.acquaviva.org  </a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.acquaviva.org  " target="_blank"><img border="0" src="/rep/editori/acquaviva.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Area Acquviva UISP</strong>
				           </dt>
				           <dd>
				            unione italiana sport 
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.canoashop.com">www.canoashop.com</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.canoashop.com" target="_blank"><img border="0" src="/rep/editori/logo-canoashop.gif" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">canoashop.com </strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.canoaclubmilano.it">www.canoaclubmilano.it</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.canoaclubmilano.it" target="_blank"><img border="0" src="/rep/editori/ccm.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Canoa Club Milano</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.scuoladicanoa.it">www.scuoladicanoa.it</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.scuoladicanoa.it" target="_blank"><img border="0" src="/rep/editori/onda_blu.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Onda Blu Canoa & Rafting ASD</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <img src="/img/logo_bn.jpg">
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">ASD Marina di Candeli</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">Alberto</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/garzena.png"  rel="thumbnail"><img border="0" src="/rep/editori/garzena.png" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Alberto Garzena</strong>
				           </dt>
				           <dd>
				            CC Biella
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.assex.it/">www.assex.it/</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <img src="/img/logo_bn.jpg">
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Roma Assex Canoa Kayak</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.sottocosta.it/">www.sottocosta.it/</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.sottocosta.it/" target="_blank"><img border="0" src="/rep/editori/tatiana_cappucci.png" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Tatiana Cappucci</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.addadventure.it">www.addadventure.it</a></div><span style="float:right">kayak68</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="http://www.addadventure.it" target="_blank"><img border="0" src="/rep/editori/stefano_caprari.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Stefano Caprari</strong>
				           </dt>
				           <dd>
				            addaventure.it
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"><a target="_blank" href="http://www.gene17kayaking.com/">www.gene17kayaking.com/</a></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <img border="0" src="http://forum.ckfiumi.net/index.php?action=dlattach;attach=1300;type=avatar">
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Simon Westgarth</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/JC.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/JC.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Giorgio Jandolo Cossu</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameA">Gold++ Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">maurino</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/mauro_denotti.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/mauro_denotti.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Mauro Denotti</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">Anselmo</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/anselmo_braga.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/anselmo_braga.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Anselmo Braga</strong>
				           </dt>
				           <dd>
				            Kayak Team Turbigo
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">Marco</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <img src="/img/logo_bn.jpg">
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Marco Lascialfari</strong>
				           </dt>
				           <dd>
				            ASD Marina di Candeli
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/max_milani.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/max_milani.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Milani Max </strong>
				           </dt>
				           <dd>
				            Canoa Club Milano
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">Michele Ramazza</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/mramazza.png"  rel="thumbnail"><img border="0" src="/rep/editori/mramazza.png" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Michele Ramazza</strong>
				           </dt>
				           <dd>
				            Canoa Club Bologna
				           </dd>
				    	   <dt ><span class="uNameB">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/Tiziano.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/Tiziano.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Tiziano </strong>
				           </dt>
				           <dd>
				            Cus Pavia
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/me.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/me.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Marco Bolognesi</strong>
				           </dt>
				           <dd>
				            Sarca Marines Team
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/giuliano_bruschi.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/giuliano_bruschi.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Giuliano Bruschi</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">cortez</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/cortesi_alessio.png"  rel="thumbnail"><img border="0" src="/rep/editori/cortesi_alessio.png" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Alessio Cortesi</strong>
				           </dt>
				           <dd>
				            Trezzo Kayak
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/paolo_costantini.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/paolo_costantini.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Paolo Costantini</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/Mauri.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/Mauri.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Mauri Dipietro</strong>
				           </dt>
				           <dd>
				            Cus Pavia
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">lucaswim</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/luca_perondi.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/luca_perondi.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Luca Perondi</strong>
				           </dt>
				           <dd>
				            Trezzo Kayak
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/rivis_fabri.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/rivis_fabri.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Fabrizio Rivis</strong>
				           </dt>
				           <dd>
				            Canoa Club Trento
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <img src="/img/logo_bn.jpg">
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Luca Tinti</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		  	<li class="resourceListItem" >
		    		<ul>
				      <li class="uName{Donors_tipo}" style="background-color:#D0D0DA;list-style : none;">
				        <div class="link_donors"></div><span style="float:right">&nbsp;</span>
				      	<div style="clear:both"></div>
						</li>
				      <li class="uAvatar">
				       <a href="/rep/editori/milena_velati.jpg"  rel="thumbnail"><img border="0" src="/rep/editori/milena_velati.jpg" /></a>
				      </li>
				      <li class="uInfo">
				        <dl>
				           <dt>
				            <strong class="fn">Milena Velati</strong>
				           </dt>
				           <dd>
				            &nbsp;
				           </dd>
				    	   <dt ><span class="uNameC">Gold Member</span>  </dt>
				        </dl>
				      </li>
					</ul>
		 	 </li>
			
		</ul>
	</div>
	
</div>
	
	

				<!-- END  CONTENTS -->
			</div>
			</td>
        	<td class="dxCol">
				<!-- INIZIO MENU DX -->
			<div id="menudx">
			<ul>
				<li class="menu"><a href="/login.phtml">Login</a></li>
				<li class="menu"><a href="/registra.phtml">Registrati</a></li>
				<li class="menu"><a href="/recupera.phtml">Recupera Password</a></li>
				<li class="menu"><a href="/help.phtml">Come Funziona</a></li>
				<li class="submenu_selected_U"><a href="/madeby.phtml">Chi siamo</a></li>
				<li class="menu"><a href="/show.phtml">Lista Editori</a></li>
			</ul>
			</div>
			<div class="textWel">
		 	 <a href="/registra.phtml">Diventa anche tu un editore!</a>
		  	</div>	
			<div class="textWel" style="font-size:12px">
			<p>Come sapete abbiamo deciso di provare a sostenere CKfiumi con l'aiuto di chi CKfiumi lo usa: il popolo dei canoisti. 
			Per far questo abbiamo deciso di stampare degli adesivi e di creare la lista dei Members  rendendo pubblica la lista su CKfiumi, un po' come avviene su sito degli amici del Brianza Tour dal quale candidamente ammetto ho ripreso l'idea.
			<br/><br/>
			  (<a href="http://forum.ckfiumi.net/index.php?topic=635.0">continua</a>)
			<br/><br/>

			E' da poco attivo il contro corrente dell'associazione.
			I dati per effettuare bonifici sul  conto corrente  sono:<br />
			<br/>
			<b>a favore di :  CKFIUMI <br />
			IBAN   IT35F0316501600000110493474</b>
			<br /><br />
			E' la coordinata bancaria internazionale che consente di identificare, in modo univoco, il Conto Corrente
			<br />

			<br/><br/>
			un sentito ringraziamento a tutti 
			<br/>
			Massimo e Philo per Ckfiumi	
			</p>
			</div>
			<div class="textWel" style="font-size:12px">
			PS: visto il disguido della raccolta iniziale che ci ha colti un poco impreparati, 
			se non vedi il tuo nome tra i donatori <a href="/contatto.phtml">contattaci</a>
			<br/> Ciao!!! 
			</div>
<!-- FINE MENU DX -->		

			</td>
      	</tr>
    	</table>
	</div>
	<!-- END MAIN AREA -->
		<!-- INIZIO FOOTER -->
		<div id="footer">
		      <p><a href="/">home</a> &#8226;  
			  <a href="/fiume.phtml">fiumi</a> &#8226; 
			  <a href="/ricerca.phtml">ricerca fiumi</a> &#8226;
			  <a href="/help.phtml">come funziona</a>  &#8226;
			  <a href="/gradi.phtml">I gradi WW</a> &#8226; 
			  <a href="/contatto.phtml">scrivici</a> &#8226; 
			  <a href="/profilo.phtml/dani">webmaster</a>  
			  </p>
				<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o 
			pubblicazione  anche parziale per fini commerciali<br/>
			</p>
	<p class="loghi"><a href="/redirect.phtml?target=firaft" rel="nofollow"><img src="/img/sponsor/firaft.jpg" style="border:0px" alt="FIRAFT"/></a>
	&nbsp;<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="http://www.ckfiumi.net/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	</p>
		</div>
	</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-666569-2";
urchinTracker();
</script>
</body>
</html>


