
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Ckfiumi :: Mercatino CKI: canoe kayak usati e non </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa,"/>
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..."/>
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0="/>
<link href="css/A.defaults.css.pagespeed.cf.fmQPojuK-r.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="js/all-1.js.pagespeed.jm.oQxXBlF1gD.js"></script>
<script type="text/javascript">if(top.location!=location){top.location.href=document.location.href;}</script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
<div id="mainFront">
<img id="a" src="img/header/01.jpg.pagespeed.ce.9un7t2RvTN.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
</div>
<div id="containerMenu"><div id="menu_left"><img src="img/xsfondo_barra_sx.gif.pagespeed.ic.pDJxMOJcbI.png" alt=""/></div><div id="menu_right"><img src="img/xsfondo_barra_dx.gif.pagespeed.ic.5a2WR5Ag1k.png" alt=""/></div><div id="menu_orizz">
<a class="menu" href="/">Home</a> |
<a class="menu" href="fiume.phtml">Fiumi</a> |
<a class="menu" href="news/calendario.phtml">Appuntamenti</a> |
<a class="menu_selected_U" href="mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
<a class="menu" href="http://forum.ckfiumi.net">Forums CKI</a> |
<a class="menu" href="racconti.phtml">Vita di Fiume</a> |
<a class="menu" href="contatto.phtml">Scrivici</a> |
<a class="menu" href="login.phtml">Login</a> |
</div>
</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->
<!-- BEGIN MAIN AREA -->
<div id="main">
<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
<tr>
<td class="sxCol">
<div id="elCont">
<div id="elCont_left" class="z_consultaForum"></div><div id="elCont_right">Nuovo Mercatino di CKI !</div>
</div>
<div id="sottoElCont">
<form id="LOC" action="/mercatino.phtml" method="post" enctype="multipart/form-data">
<!-- BEGIN  CONTENTS -->
<br/>
<script type="text/javascript">function otherImage(par){$('img_tipo').src="/img/"+par+".jpg";}</script>
<script language="javascript">var currentTabId='V';function enableTab(id){if(id==currentTabId){return;}
obj=document.getElementById('panel'+id);obj.className="visiblePanel";obj=document.getElementById('tab'+id);obj.className="visibleTab";obj=document.getElementById('panel'+currentTabId);obj.className="hiddenPanel";obj=document.getElementById('tab'+currentTabId);obj.className="hiddenTab";currentTabId=id;}</script>
<div style="width:100%;border: 1px solid;background:#A5A8B5;height:55px">
<div style="float:left;width:56%;color:white">Invitiamo chiunque abbia o cerchi kayak o canoe usati ad inserire il proprio annuncio con i dati relativi all' offerta o ricerca.
</div>
<div style="float:right;padding: 10px 4px 0px 0px">
<a href="mercatino.phtml?mct_status=2"><img src="img/xnuovo_annuncio.gif.pagespeed.ic.0jaGzKzoF1.png" alt="mercatino ckfiumi" border="0"/></a>
</div>
</div>
<div class="tab_container">
<table style="margin-top:2px" width="100%" cellpadding="0" cellspacing="0" border="0" align="left">
<tr>
<td id="tabV" class="visibleTab" onClick="enableTab('V')"><span class="simulate_href">Vendesi</span></td>
<td id="tabC" class="hiddenTab" onclick="enableTab('C')"><span class="simulate_href">Cercasi</span></td>
<td id="tabA" class="hiddenTab" onclick="enableTab('A')"><span class="simulate_href">In più</span></td>
<td class="emptyTab">&nbsp</td>
</tr>
</table>
<div id="panelV" class="visiblePanel">
<span style="clear:both"><img src="img/V.jpg"></span>
<div class="contenitore_merc">
<a href="#" name="6448"></a>
<div class="data">
<div style="float:left">&nbsp;ricardougarteche@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 25/05/12</div>
</div>
<div class="estremi">
ugarteche riccardo
<br/>3335772387
<br/>Lucca
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo due kayak al prezzo di 450,kayak zulu usato,kayak dna pari al nuovo,con una pagagia e un paraspruzi.non tratt.<br/>
<br/>
vendo giacca artistic,pantalone ozone,maglia neoprene,maglia invernale,aiuto al gallegiamento,casco,calzino in neoprene,guanti in neoprene,sottocasco,condizione pari al nuovo,usati due volte.tutto a 250 euro, non tratt.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6447"></a>
<div class="data">
<div style="float:left">&nbsp;cariellocarmine@hotmail.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 25/05/12</div>
</div>
<div class="estremi">
carmine cariello
<br/>3479683305
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo Kayak dagger honcho da fiume e da mare Ottimo stato...vero affare..prezzo euro 350. abito Comune di Castagneto Carducci (LI)
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6446"></a>
<div class="data">
<div style="float:left">&nbsp;luca.yak@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Lucs</span><b>Vendo</b> annuncio del : 24/05/12</div>
</div>
<div class="estremi">
luca bruschi
<br/>3334274538
<br/>Lecco
<br/><a href="rep/mercatino/32ca390616281d1f07c2a977ac3819c9/SDC16995.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/32ca390616281d1f07c2a977ac3819c9/thumb_SDC16995.JPG"/></a></div>
<div class="annuncio">
Pyranha Burn M bianco azzurra.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6443"></a>
<div class="data">
<div style="float:left">&nbsp;alessandrozocchi@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 23/05/12</div>
</div>
<div class="estremi">
alessandro zocchi
<br/>
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo DAGGER GREEN BOAT, perfette condizioni a € 650.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6442"></a>
<div class="data">
<div style="float:left">&nbsp;luca.yak@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 23/05/12</div>
</div>
<div class="estremi">
luca bruschi
<br/>3334274538
<br/>Lecco
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Pyranha BURN M bianco-azzurra tenuta bene.600 Eurs!<br/>
Metto foto...
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6441"></a>
<div class="data">
<div style="float:left">&nbsp;paolo.pagani5@tin.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 23/05/12</div>
</div>
<div class="estremi">
paolo pagani
<br/>3316011495
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo canoa da fiume Stubby della Wave Sport in buone condizioni e pagaia Tempest in carbonio nuova a 600 euro.<br/>
La canoa e' visionabile nei we in valsesia a casa mia a Failungo Superiore quindi chi volesse prendere due piccioni con una fava guarda la canoa e poi si fa una bella discesa sul sesia.<br/>
Per info chiamatemi sul 3316011495 Paolo<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6440"></a>
<div class="data">
<div style="float:left">&nbsp;domiziosoliani@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 22/05/12</div>
</div>
<div class="estremi">
Domizio
<br/>3484112357
<br/>Reggio Emilia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo 2 pagaie da canadese slalom a 110 euro tutte e due
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6439"></a>
<div class="data">
<div style="float:left">&nbsp;campioncino79@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 22/05/12</div>
</div>
<div class="estremi">
simone
<br/>3483238551
<br/>Lucca
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo sit on top, monoposto con pala azzali turismo in legno.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6437"></a>
<div class="data">
<div style="float:left">&nbsp;bertola.paolo@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 22/05/12</div>
</div>
<div class="estremi">
Paolo Bertola
<br/>3280013901
<br/>Como
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo SUP più pagaia Dragorossi in ottime condizioni colore giallo (o verde) con gavone a 300€ non trattabili.<br/>
Causa: inutilizzo<br/>
Paolo
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6436"></a>
<div class="data">
<div style="float:left">&nbsp;massimonani@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 22/05/12</div>
</div>
<div class="estremi">
Massimo Nani
<br/>3393723747
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak K1 in vetroresina ottima velocita, molto leggiero e manovrabile. <br/>
<br/>
Il kayak è lungo 4.20 m, si carica senza problemi anche su una macchina di piccola stazza senza sforare le misure e le % riguardanti la normativa sui carichi sporgenti, è dotato di una sacca antiaffondamento gonfiabile, posizzionata nella parte posteriore dello scafo, stringhe elastiche anteriori e posteriori per il fermo di oggetti. Ho applicato un punto di appogio in vertoresina e alluminio per la spinta dei piedi e il bilanciamento dello scafo. Insieme cedo anche il para spruzzi da agganciare allo scafo e stringere alla vita e il copri pozzo per i trasporti in tessuto impermeabile. <br/>
<br/>
foto<br/>
http://img341.imageshack.us/img341/5825/img0264bq.jpg<br/>
http://img600.imageshack.us/img600/3621/img0259pw.jpg
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6432"></a>
<div class="data">
<div style="float:left">&nbsp;fulvio.guarino@unicredit.eu </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
fulvio guarino
<br/>3931860152
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo pagaia Mitchel Blades mod. Genesis, manico dritto, 194 cm, gialla. nuova, mai usata. 150 euro non trattabili
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6431"></a>
<div class="data">
<div style="float:left">&nbsp;fulvio.guarino@unicredit.eu </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
fulvio guarino
<br/>3931860152
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo Pagaia Robson Magnum blu 194 cm. nuova, mai usata. 140 euro
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6430"></a>
<div class="data">
<div style="float:left">&nbsp;fulvio.guarino@unicredit.eu </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
fulvio guarino
<br/>3931860152
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo Rainbow mod. ZULU, rossa, 8 mesi di vita. 15 discese. ottime condizioni. 350 euro.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6429"></a>
<div class="data">
<div style="float:left">&nbsp;bittern@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
Mimmo Marelli
<br/>
<br/>Novara
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo kayak doppio in HTP Prijon Poseidon colore rosso; in ottimo stato, con timone e copripozzetto<br/>
Per caratteristiche vedere il sito web Prijon<br/>
Prezzo 950 euro, non spedisco
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6427"></a>
<div class="data">
<div style="float:left">&nbsp;sfn.pgz@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
Stefano Pigozzi
<br/>3928146183
<br/>Trento
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Kayak Sanblas corto in buone condizioni completo di sacche di galleggiamento, para spruzzi, casco, salvagente, pagaia e carrello ad € 449.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6426"></a>
<div class="data">
<div style="float:left">&nbsp;laieli@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: eli</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
sergio
<br/>329 0313791
<br/>Verbano Cusio Ossola
<br/><a href="rep/mercatino/af79f064b1d4e1d3943df59468234caf/vector2.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/af79f064b1d4e1d3943df59468234caf/thumb_vector2.jpg"/></a></div>
<div class="annuncio">
vendo Vector in ottime cond pari al nuovo<br/>
vedi foto €. 300,00 visibile a Domodossola.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6425"></a>
<div class="data">
<div style="float:left">&nbsp;enricotorn@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
Enrico
<br/>
<br/>Perugia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendesi canoa slalom Caiman Premier 360,<br/>
condizioni pari al nuovo più custodia per il trasporto, euro 600. Contattatemi per foto o info su contatto mail. Vendesi per inutilizzo<br/>
<br/>
<br/>
<br/>
<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6424"></a>
<div class="data">
<div style="float:left">&nbsp;niser80@hotmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: niser80</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
nicolas
<br/>3484594471
<br/>Aosta
<br/><a href="rep/mercatino/8a1c68f8535b1eb0093e1db634c09880/20120325_011.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/8a1c68f8535b1eb0093e1db634c09880/thumb_20120325_011.jpg"/></a></div>
<div class="annuncio">
vendo kayak wave sport FUSE56 in ottime condizione a 620 euro. si trova ad aosta, posibilita di spedizione. per piu foto scrivetemi.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6423"></a>
<div class="data">
<div style="float:left">&nbsp;bittern@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
Mimmo Marelli
<br/>
<br/>Novara
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo kayak doppio Prijon mod. Piave in kewlar-carbon, usato, con piccole riparazioni di routine ma in ottimo stato; con timone, copripozzetti e sacco di punta per la prua (ha un solo gavone a poppa)<br/>
Per le caratteristiche vedere il sito web della Prijon<br/>
Prezzo 950 euro: non spedisco
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6422"></a>
<div class="data">
<div style="float:left">&nbsp;stortimariano@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 20/05/12</div>
</div>
<div class="estremi">
Mariano Storti
<br/>3331924191
<br/>Vicenza
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo paraspruzzi ozone ottimo stato taglia s, euro 25
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6421"></a>
<div class="data">
<div style="float:left">&nbsp;augusto.zocchi@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 20/05/12</div>
</div>
<div class="estremi">
augusto zocchi
<br/>3292337533
<br/>Ancona
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo canoa a due posti in vetroresina discrete condizioni lunga 5 metri 2 gavoni<br/>
visibile in ancona euro 600
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6420"></a>
<div class="data">
<div style="float:left">&nbsp;lucilella2010@virgilio.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: pippolo</span><b>Vendo</b> annuncio del : 20/05/12</div>
</div>
<div class="estremi">
Luciano
<br/>3385964850
<br/>Firenze
<br/><a href="rep/mercatino/d879c1763a0812ee931ca7ed16377c50/Immag046.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/d879c1763a0812ee931ca7ed16377c50/thumb_Immag046.jpg"/></a></div>
<div class="annuncio">
Vendo Pyranha Burn S, comprata nel 2011 a 600 euro
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6418"></a>
<div class="data">
<div style="float:left">&nbsp;bittern@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 19/05/12</div>
</div>
<div class="estremi">
Mimmo Marelli
<br/>
<br/>Novara
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak da mare - lago - fiume lento Prijon Millenium colore giallo, scafo bianco, praticamente nuovo, usato una decina di volte su lago; costruzione in vetroresina; condizioni più che ottime; acquistato nel giugno 2011 quindi con un anno di garanzia residua; prezzo 950 euro.<br/>
A chi desidera, mando foto.<br/>
Per altre caratteristiche del modello vedere il sito web della Prijon.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6416"></a>
<div class="data">
<div style="float:left">&nbsp;m.fassi@lorisbellini.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 19/05/12</div>
</div>
<div class="estremi">
fassi mauro
<br/>3482352304
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo (per mancanza di seguaci!) kayak a 2 posti da mare/lago. mod. nova caribe2 2005, giallo, usato poco, mai in fiume, segni di normale usura sul fondo. € 300. foto disponibili a richiesta.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6414"></a>
<div class="data">
<div style="float:left">&nbsp;riccardo_santoni@virgilio.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 19/05/12</div>
</div>
<div class="estremi">
Riccardo Santoni
<br/>
<br/>Ancona
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak lungo 4,60 largo 60 cm stabile in acque agitate malleabile e veloce in mare calmo vero affare vendo 350 euro .
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6413"></a>
<div class="data">
<div style="float:left">&nbsp;alessandrozocchi@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 18/05/12</div>
</div>
<div class="estremi">
alessandro zocchi
<br/>
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo giacca stagna IMMERSION RESEARCH taglia XL, colore verde kiwi/grigio e pantalone semistagno grigio, il tutto in perfette condizioni. Giacca € 150, pantalone € 90
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6412"></a>
<div class="data">
<div style="float:left">&nbsp;er_bacci@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: er bacci</span><b>Vendo</b> annuncio del : 18/05/12</div>
</div>
<div class="estremi">
andrea tosatti
<br/>3289027386
<br/>Genova
<br/><a href="rep/mercatino/3f82ee60588ce246bda5dc2163dedfbe/Foto0347.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/3f82ee60588ce246bda5dc2163dedfbe/thumb_Foto0347.jpg"/></a></div>
<div class="annuncio">
vendo maglia con protezione per le spalle incorporata. usata 2 volte. prezzo nuova 110 euro la vendo a 40 non trattabili. è da mountain bike ma adattabile alla canoa
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6411"></a>
<div class="data">
<div style="float:left">&nbsp;biker74@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 18/05/12</div>
</div>
<div class="estremi">
Nicola
<br/>3477934119
<br/>Pavia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo canoa marca bg-canoe modello am6 usata solo 2 volte per mancanza di tempo barca perfetta stabile veloce e leggera<br/>
possibilità di prova<br/>
richiesti euro €400 leggermente trattabili<br/>
invio foto su richiesta
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6410"></a>
<div class="data">
<div style="float:left">&nbsp;f_paperini@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 18/05/12</div>
</div>
<div class="estremi">
Federico Paperini
<br/>3398641264
<br/>Terni
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Kayak da fiume Wave Sport DIESEL 75. è in buone condizioni, lo scafo non ha preso mai botte e non ha mai subito riparazioni. il prezzo è di 400€.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6409"></a>
<div class="data">
<div style="float:left">&nbsp;giacomokayak@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Canapone</span><b>Vendo</b> annuncio del : 18/05/12</div>
</div>
<div class="estremi">
Giacomo
<br/>
<br/>Livorno
<br/><a href="rep/mercatino/9a2b5a1a7b77bede2a31e01877ece238/Salto_front.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/9a2b5a1a7b77bede2a31e01877ece238/thumb_Salto_front.jpg"/></a></div>
<div class="annuncio">
OCCASIONE kayak Eskimo Salto Evo, buone condizioni,<br/>
solo normali graffi. Usata poco, aggiunto schienale regolabile e porta borraccia-corda da lancio. Lung 249, larg 64, vol 280.<br/>
Vendo 600 euro.<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6405"></a>
<div class="data">
<div style="float:left">&nbsp;porticciolosurf@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 17/05/12</div>
</div>
<div class="estremi">
fabrizio rombj
<br/>3496806655
<br/>Genova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo il seguente materiale:<br/>
- Surfkayak Mega Merlin in kevlar carbonio, ottime condizioni, 450 Euro<br/>
- Pagaia SCHLEGEL, anticipata 45 gradi, indistruttibile, 50 Euro<br/>
- Sacca per trasporto kayak 50 Euro.<br/>
- Giacca Hiko Carina taglia L come nuova 100 Euro.<br/>
550 euro per il kit completo<br/>
Le foto sono disponbili su richiesta.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6404"></a>
<div class="data">
<div style="float:left">&nbsp;gesualdi.nicola@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 17/05/12</div>
</div>
<div class="estremi">
Nico
<br/>3461534183
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Salvagente di gamma alta per competizioni slalom e discesa.<br/>
Ideale per discesa.<br/>
Disegno anteriore a basso profilo per passare sotto la palina con facilità, disegno posteriore stretto per lasciare libero il movimento delle spalle. BLU. 50 euro.<br/>
Imbottitura in Airex morbidissimo per una perfetta aderenza e vestibilità.<br/>
<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6403"></a>
<div class="data">
<div style="float:left">&nbsp;forintomas@virgilio.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 16/05/12</div>
</div>
<div class="estremi">
forin tomas
<br/>3481725414
<br/>Padova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak RIOT Thunder 76 color arancio in ottimo stato Euro 480,00.. posso inviare foto contattatemi<br/>
forintomas@virgilio.it 3481725414
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6402"></a>
<div class="data">
<div style="float:left">&nbsp;maffezzoli.davide@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 16/05/12</div>
</div>
<div class="estremi">
Davide Maffezzoili
<br/>3277834291
<br/>Mantova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo 2 pyranha:<br/>
-Blade gialla a 150 euro<br/>
-Ammo bianco-azzurra, quasi nuova, misura M, a 500 euro.<br/>
Inoltre una pagaia ainsworth,pressochè nuova,con manico a doppia piega.Bellissima, ma troppo lunga-200cm. Vendo a 170 euro.<br/>
Posso inviare foto<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6398"></a>
<div class="data">
<div style="float:left">&nbsp;f.lupi1@virgilio.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 16/05/12</div>
</div>
<div class="estremi">
Francesco Lupi
<br/>3476672903
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak da mare Qajaq modello Sardinia pozzetto grande colore bianco con profilo nero. Ottime condizioni. Visibile a Piombino<br/>
Prezzo 1300 euro<br/>
A richiesta posso fornire foto per email
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6397"></a>
<div class="data">
<div style="float:left">&nbsp;rizzigo@tin.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Gigi Rizzi</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Gigi Rizzitelli
<br/>3472411803
<br/>Mantova
<br/><a href="rep/mercatino/d17679d095df278beed00a01cdf87951/03042012207.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/d17679d095df278beed00a01cdf87951/thumb_03042012207.jpg"/></a></div>
<div class="annuncio">
OCCASIONE PYRANHA MOLAN M. Kayak di ultima generazione, come nuova, usata solo in spot e piscina. Vendo a 550,00 euro Lunghezza cm 182, volume lt 214 ( 56 galloni), peso kg 14, range peso paddler kg 50-90.<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6395"></a>
<div class="data">
<div style="float:left">&nbsp;alepruzzo@hotmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: AlexGenova</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Alessio Pruzzo
<br/>342/3565883
<br/>Genova
<br/><a href="rep/mercatino/e48f016e670c3a475d85eac04c4e597b/140220121019.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/e48f016e670c3a475d85eac04c4e597b/thumb_140220121019.jpg"/></a></div>
<div class="annuncio">
Vendesi causa inutilizzo Kayak "Janautica Alaska con Gavone" e pagaia "Azzali Standard". Il tutto è stato usato due volte ed è come nuovo. Visibile a Genova Murcarolo. 250 Euro Cell: 342/3565883
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6393"></a>
<div class="data">
<div style="float:left">&nbsp; </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
SERGIO
<br/>3928307750
<br/>Brescia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
BIGDOG VENDO 450 EURO USATA POCHISSIMO X LAVORO E INPEGNI DISPONGO ANCHE DI ATREZZATURA E ABBIGLIAMENTO PALM XXL A PARTE PREZZI TROTTABILI.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6392"></a>
<div class="data">
<div style="float:left">&nbsp;enricomarinz@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Enrico Marini
<br/>3483714266
<br/>Padova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo pyranha attak! colore arancione e ben tenuta<br/>
a euro 200 trattabili
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6391"></a>
<div class="data">
<div style="float:left">&nbsp;enricomarinz@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Enrico Marini
<br/>3483714266
<br/>Padova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Dragorossi Mafia,tenuta bene e tagliandata! bella e divertente canoa a euro 300<br/>
ciao
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6390"></a>
<div class="data">
<div style="float:left">&nbsp;andrea@wwsclothing.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: wwsclothing</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Andrea
<br/>
<br/>Genova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo exo pin up usata 2 volte colore rosso prezzo 350 euro
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6389"></a>
<div class="data">
<div style="float:left">&nbsp;maslug@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: maslug</span><b>Vendo</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Massimiliano
<br/> 39 328 6754209
<br/>Lucca
<br/><a href="rep/mercatino/36a5167dc33abd251ad067cec191f09a/P1010414.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/36a5167dc33abd251ad067cec191f09a/thumb_P1010414.JPG"/></a></div>
<div class="annuncio">
Habitat 74 rossa, in buonissime condizioni vendesi EURO 500,00
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6388"></a>
<div class="data">
<div style="float:left">&nbsp;ilpiroa@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: piroa</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
Antonio
<br/>3472294833
<br/>Vicenza
<br/><a href="rep/mercatino/b02fb20e4af79abe7e791a8bb00dc885/IMG_9731.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/b02fb20e4af79abe7e791a8bb00dc885/thumb_IMG_9731.JPG"/></a></div>
<div class="annuncio">
PERMUTO Kayak pyranha inazone 222, con kayak da torrente di maggior volume.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6387"></a>
<div class="data">
<div style="float:left">&nbsp;alessandrozocchi@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
alessandro zocchi
<br/>
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo salvagente ASTRAL GREEN Tg. L/XL in perfette condizioni a € 150 corda da lancio ASTRAL su misura per tasca frontale a € 30.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6386"></a>
<div class="data">
<div style="float:left">&nbsp;kayak88k@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
Claudio Massarutto
<br/>3497949530
<br/>Venezia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
VENDO vari k1 discesa (da gara), in discrete condizioni a €100 l'uno, buoni soprattutto per chi vuole fare del turismo veloce in fiume, mare e lago o per chi intende avvicinarsi all'agonismo.<br/>
Invio foto su richiesta.<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6385"></a>
<div class="data">
<div style="float:left">&nbsp;gabrygxt@hotmail.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
gabriele benacchio
<br/>3280321833
<br/>Vicenza
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
valstagna (vicino bassano del grappa) vendo pagaia robson stud da rodeo del 2010 MAI usata. manico antiscivolo nero e pale arancioni. lunghezza 192cm<br/>
chiamate o scrivete x foto....vendo a 160€...affare....é nuova
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6384"></a>
<div class="data">
<div style="float:left">&nbsp;grandemug@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Dany CCAL</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
Daniele Ravera
<br/>3333690688
<br/>Alessandria
<br/><a href="rep/mercatino/e7cce2905c68efb9b8084fdc4707dce0/madboy.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/e7cce2905c68efb9b8084fdc4707dce0/thumb_madboy.jpg"/></a></div>
<div class="annuncio">
Vendo Dragorossi Madboy usata pochissimo e massimo su III grado. completa di sacchi di galleggiamento.<br/>
500 euro.<br/>
Valuto eventuale scambio con Mountain bike
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6383"></a>
<div class="data">
<div style="float:left">&nbsp;francescocanoa@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
iraci francesco
<br/>3381431273
<br/>Padova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo vario materiale da kayak x ragazzi. max 10-12 anni. mio figlio ora ha 14 anni x interderci.<br/>
giacca h20 in naylon ozone rossa, giacca nookie in neoprene bifoderato con paraspruzzi incorporato. pagaie double douch in carbonio(manico e pale) pagaia con manico e pale in fibra della propulsion. salvagente ozone con imbragatura. n. 2 mute corte, mezze braccia e mezze gambe della tribord. ecc. tutto a prezzi validi e tenuto molto bene. ripeto usati da un ragazzino che andava in h2o solo con suo padre. se interesati telefonate. un saluto francesco limena pd.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6382"></a>
<div class="data">
<div style="float:left">&nbsp;meablues@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: meablues</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
Michele Della Mea
<br/>328 0211803
<br/>Pisa
<br/><a href="rep/mercatino/44519777adc0a478ff72c5477eeeed16/salvagenti.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/44519777adc0a478ff72c5477eeeed16/thumb_salvagenti.jpg"/></a></div>
<div class="annuncio">
Vendo causa cambio due salvagenti un Palm Fusion taglia L/XL freestyler usato ma tenuto bene,e un Palm Sembyant W/W taglia XL/XLL pari al nuovo usato quasi mai .Il tutto a 80 euro .telefonare 3280211803 meablues@alice.it
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6381"></a>
<div class="data">
<div style="float:left">&nbsp;paminav@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: pamiuska</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
pamina vitta
<br/>3406949061
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo:<br/>
<br/>
-Wave Sport HABITAT 75 colore verde - ottime condizioni (come nuova) - 750€<br/>
<br/>
MATERIALE VARIO<br/>
-Giacca d'acqua semistagna (polsini in lattice - no lattice al collo) PALM LARA taglia M colore celeste NUOVA mai usata €100 http://www.palmequipmenteurope.com/gear/lara.html<br/>
<br/>
-PARASPRUZZI usato 60€ (taglia in vita S, pozzetto LARGE)<br/>
<br/>
-giacca d'acqua stagna Bomber Gear - usata - colore rosso € 70.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6380"></a>
<div class="data">
<div style="float:left">&nbsp;chiticlaudio@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
Claudio Chiti
<br/>3337119456
<br/>Firenze
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo kayak pyranha razor colore giallo usata <br/>
ma in ottime condizioni 300 euro<br/>
contattare per foto
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6379"></a>
<div class="data">
<div style="float:left">&nbsp;gpmazz@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 14/05/12</div>
</div>
<div class="estremi">
Giampaolo Mazzaglia
<br/>3339051256
<br/>Massa-Carrara
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo salvagente Hiko Swift taglia L/XL nero, condizioni pari al nuovo, ad euro 25. Possibile ritiro anche a Firenze.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6378"></a>
<div class="data">
<div style="float:left">&nbsp;antonello.colzani@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
Antonello Colzani
<br/>3357802613
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Pyranha Attack colore azzurro l'ho usata molto poco. Adoperata sempre e solo a fine rapida per giocare con la corrente.<br/>
Mai fatto discese, salti.<br/>
E' completa di punta piedi,premicosce segiolino e schienale originali e regolabili. Sacche di galleggiamento. Tappo avvita svita svuota acqua.<br/>
euro 380<br/>
Il kayak è visibile in Brianza vicino a Monza.<br/>
Avrei anche un Prijon Hurricane praticamente nuovo anche questo, di colore blu completo degli accessori come sopra<br/>
euro 300<br/>
Antonello 3357802613
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6377"></a>
<div class="data">
<div style="float:left">&nbsp;carlo.ferlenghi@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Carlo Ferlenghi </span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
carlo fgerlenghi
<br/>3282133616
<br/>Genova
<br/><a href="rep/mercatino/9c8c6921ca8baba2751d9dd8c20a5dd1/foto_001.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/9c8c6921ca8baba2751d9dd8c20a5dd1/thumb_foto_001.jpg"/></a></div>
<div class="annuncio">
vendesi outrigger oc2 oracle costr Allwave modello top in carbonio 17 kg nuova per foto info vedi tel mail
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6375"></a>
<div class="data">
<div style="float:left">&nbsp;christianox78@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Chris</span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
Christian
<br/>
<br/>Cuneo
<br/><a href="rep/mercatino/c49e2245c878404161596e76befe5acc/_DSC0627.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/c49e2245c878404161596e76befe5acc/thumb__DSC0627.JPG"/></a></div>
<div class="annuncio">
Kayak Perception Overflow Corsica ,<br/>
pagaia Prjion Kinetic sacchi di galleggiamento, tutto a 200 euro <br/>
per info contatto via mail
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6373"></a>
<div class="data">
<div style="float:left">&nbsp;tomtrento@vodafone.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: tomtrento</span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
fabrizio
<br/>0461944580
<br/>Trento
<br/><a href="rep/mercatino/332675992c4891a7e2b35b9e07bdeb9f/pagaia_werner.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/332675992c4891a7e2b35b9e07bdeb9f/thumb_pagaia_werner.jpg"/></a></div>
<div class="annuncio">
pagaia Werner Player river running 200 cm.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6372"></a>
<div class="data">
<div style="float:left">&nbsp;robgala@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
roberto galassini
<br/>
<br/>Modena
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo muta Mares III° misura , come nuova , 5 mm.,<br/>
con cappuccio, ideale per hydrospeed , usata comunque solo pre immersioni a euro 150
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6371"></a>
<div class="data">
<div style="float:left">&nbsp;robgala@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
roberto galassini
<br/>3391040002
<br/>Modena
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo Pinball rossa e gialla ,come nuova perchè usata solo in piscina , con copripozzetto originale, a euro 250.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6370"></a>
<div class="data">
<div style="float:left">&nbsp;nardi.enrico@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: enrimystic</span><b>Vendo</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
Enrico
<br/>3479853041
<br/>Genova
<br/><a href="rep/mercatino/5d2681c8b1b967680f4a199d36894722/P5130239.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/5d2681c8b1b967680f4a199d36894722/thumb_P5130239.JPG"/></a></div>
<div class="annuncio">
Vendo causa inutilizzo giubotto Hiko Cinch verde taglia L/XL completo di cinghia centrale con dissipatore e sgancio rapido e fischietto.<br/>
Condizioni perfette pari al nuovo, utilizzato solo una volta in fiume.<br/>
Altre foto disponibili su richiesta.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6368"></a>
<div class="data">
<div style="float:left">&nbsp;globo69@live.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 12/05/12</div>
</div>
<div class="estremi">
Gloria
<br/>3498345878
<br/>Lodi
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
VENDO KAYAK EXO JOKER A 200 EURO <br/>
LUNGHEZZA 207 cm <br/>
LARGHEZZA 62 cm <br/>
POZZETTO Est. 84*49 cm<br/>
Int. 78*45 cm <br/>
PESO 15 Kg <br/>
PESO CANOISTA 60/80 Kg <br/>
<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6367"></a>
<div class="data">
<div style="float:left">&nbsp;alberto.borntofly@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 12/05/12</div>
</div>
<div class="estremi">
Alberto Bortolin
<br/>
<br/>Rovigo
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak da mare in fibra, gavoni stagni anteriore e posteriore, pompa svuotamento e timone. lungo più di 5 metri.<br/>
<br/>
perfetto per tutto, da chi vuole imparare a chi desidera fare lunghi tragitti.<br/>
Spedisco foto su richiesta.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6366"></a>
<div class="data">
<div style="float:left">&nbsp;laste.ilriki@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 12/05/12</div>
</div>
<div class="estremi">
riccardo pogliani
<br/>3485706701
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Kayak da discesa Mad Boy verde. <br/>
Prezzo 450€ trattabili.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6365"></a>
<div class="data">
<div style="float:left">&nbsp;carmine.sicignano@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: snoopo16</span><b>Vendo</b> annuncio del : 12/05/12</div>
</div>
<div class="estremi">
carmine
<br/>3281881917
<br/>Napoli
<br/><a href="rep/mercatino/1aff8e30c774677c3c8f07c9f7f0ee60/pinup01.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/1aff8e30c774677c3c8f07c9f7f0ee60/thumb_pinup01.jpg"/></a></div>
<div class="annuncio">
vendo in blocco o separatamente:<br/>
- EXO PINUP 2010, pressoché perfetta<br/>
- ROBSON RED FRED, discrete condizioni, con normali segni di usura <br/>
- PYRANHA S6F, riparata a <br/>
prezzo finale 650 eu
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6363"></a>
<div class="data">
<div style="float:left">&nbsp;lorenzo@kubik.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 11/05/12</div>
</div>
<div class="estremi">
Lorenzo aldeghi
<br/>3486710184
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Burn L (ultima versione 2010) Colore Blu/Bianco buone condizioni.<br/>
630 euro trattabili.<br/>
Lorenzo "il Nonno"
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6362"></a>
<div class="data">
<div style="float:left">&nbsp;maxpisani@fastwebnet.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: maxpis</span><b>Vendo</b> annuncio del : 11/05/12</div>
</div>
<div class="estremi">
Max
<br/>3936554960
<br/>Genova
<br/><a href="rep/mercatino/a01d9a2853e14857d48caf6e1409cb76/Robson_nrg.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/a01d9a2853e14857d48caf6e1409cb76/thumb_Robson_nrg.jpg"/></a></div>
<div class="annuncio">
Robson NRG XL, mt 2, canoa da rodeo per canoisti robusti. Kayak comodo, veloce anche sull'onda, rapido nelle manovre. In ottimo stato €uro 350 (eventualmente allego paraspruzzi e pagaia). Zona Genova. Il kayak è visibile a GE - Bolzaneto (se interessati visibile anche Nervi o Voltri)
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6361"></a>
<div class="data">
<div style="float:left">&nbsp;vertebrato@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 11/05/12</div>
</div>
<div class="estremi">
renzo monelli
<br/>3357774404
<br/>Mantova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo a 400 € Raimbow Funky tenuta benissimo, veloce, stabile, eskimo facile, volume medio-basso.<br/>
Grazie,<br/>
Renzo
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6359"></a>
<div class="data">
<div style="float:left">&nbsp;alepruzzo@hotmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: AlexGenova</span><b>Vendo</b> annuncio del : 10/05/12</div>
</div>
<div class="estremi">
Ale
<br/>342/3565883
<br/>Genova
<br/><a href="rep/mercatino/2c145908e0d8ca7c9e43b3223ecfcca8/140220121019.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/2c145908e0d8ca7c9e43b3223ecfcca8/thumb_140220121019.jpg"/></a></div>
<div class="annuncio">
Vendesi causa inutilizzo Kayak "Janautica Alaska con Gavone" e pagaia "Azzali Standard". Il tutto è stato usato due volte ed è come nuovo. Visibile a Genova Murcarolo. Cell: 342/3565883<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6357"></a>
<div class="data">
<div style="float:left">&nbsp;gbr.baroli@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: gabrio</span><b>Vendo</b> annuncio del : 10/05/12</div>
</div>
<div class="estremi">
gabriele baroli
<br/>3471012475
<br/>Milano
<br/><a href="rep/mercatino/e898cdae553c3144a9d9c7c1e34ff0e6/IMG_0320.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/e898cdae553c3144a9d9c7c1e34ff0e6/thumb_IMG_0320.JPG"/></a></div>
<div class="annuncio">
affarone, vendo kayak da gioco Dagger Agent 6.2 in ottimo stato completa di tutto a 450 e uri
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6356"></a>
<div class="data">
<div style="float:left">&nbsp;enricotorn@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 10/05/12</div>
</div>
<div class="estremi">
Enrico
<br/>
<br/>Perugia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendesi Salvagente shock Wave Sw150 - River Rider Cordura®, taglia L. <br/>
<br/>
Condizioni pari al nuovo usato solo 4 volte, vendesi per inutilizzo 120 euro.<br/>
<br/>
Foto su contatto mail.<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6355"></a>
<div class="data">
<div style="float:left">&nbsp;cariellocarmine@hotmail.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 09/05/12</div>
</div>
<div class="estremi">
Carmine Cariello
<br/>3479683305
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Kaiak da fiume ottimo affare. si riserva invio foto a chi e interessato chiedo euro 350<br/>
ottimo affare
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6353"></a>
<div class="data">
<div style="float:left">&nbsp;gclarizia@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
gaetano clarizia
<br/>3474366129
<br/>Salerno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo P&H delphin 155, colore arancio, visibile salerno-vietri sul mare, €1100<br/>
3474366129 gclarizia@libero.it
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6352"></a>
<div class="data">
<div style="float:left">&nbsp;fabiomata@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Mata</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
Fabio
<br/>3474879421
<br/>Milano
<br/><a href="rep/mercatino/b69e93e195a87065b98f35e4682387f7/CIMG3170.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/b69e93e195a87065b98f35e4682387f7/thumb_CIMG3170.JPG"/></a></div>
<div class="annuncio">
Casco WRS Eagle con mentoniera ,ottimo stato presenta solo qualche graffiettino sul capo.<br/>
€60
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6350"></a>
<div class="data">
<div style="float:left">&nbsp;mateusz@oriz.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
Matteo Pappalardo
<br/>3294557855
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Kayak biposto in legno, con pagaia classica.<br/>
Modelli unici di produzione artigianale anni '60.<br/>
Misure 400x80x45, con interni bianchi o verdi.<br/>
<br/>
Usati pochissime volte all'Idroscalo di Milano, quindi imballati e custoditi in rimessa.<br/>
Vendo per mancanza spazio a 990 euro, 1800 la coppia. Non effettuo spedizione.<br/>
<br/>
I kayak sono visionabili qui: <br/>
http://www.pbase.com/oriz/kayaks<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6348"></a>
<div class="data">
<div style="float:left">&nbsp;parmar@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Marcello</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
marcello
<br/>3474970438
<br/>Milano
<br/><a href="rep/mercatino/6e833885f6d4bd73baa390972abc15b2/P5080002.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/6e833885f6d4bd73baa390972abc15b2/thumb_P5080002.JPG"/></a></div>
<div class="annuncio">
Piranha Molan M anno 2011 come nuova<br/>
interni connect 30 <br/>
<br/>
750 euro <br/>
<br/>
Lunghezza cm 182, larghezza cm 64, volume lt 214 ( 56 galloni), dimensioni pozzetto cm 86x48 ( key hole ), peso kg 14, range peso paddler kg 50-90.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6345"></a>
<div class="data">
<div style="float:left">&nbsp;parmar@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Marcello</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
marcello
<br/>3474970438
<br/>Milano
<br/><a href="rep/mercatino/908e7eb388f55f5b60083072fe948219/P5080008.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/908e7eb388f55f5b60083072fe948219/thumb_P5080008.JPG"/></a></div>
<div class="annuncio">
vendo k1 slalom touch 2 carbon kevlar sottovuoto <br/>
tenuta bene a 240 euro
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6341"></a>
<div class="data">
<div style="float:left">&nbsp;rama.rock@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
Andrea Ramanzini
<br/>3480461829
<br/>Verona
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo kayak perception phat con normali segni di usura sul fondo, tenuto comunque molto bene ad euro 350. Le foto le invio su richiesta.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6340"></a>
<div class="data">
<div style="float:left">&nbsp;niser80@hotmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: niser80</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
nicolas sopranzi
<br/>3484594471
<br/>Aosta
<br/><a href="rep/mercatino/84b87827e24bbc9e36c028b30de1afe8/foto_20110209112317_11372673_big.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/84b87827e24bbc9e36c028b30de1afe8/thumb_foto_20110209112317_11372673_big.jpg"/></a></div>
<div class="annuncio">
vendo:<br/>
-giacca PALM ATOM nuove taglie M-L-XL 260 euro<br/>
-giacca PALM SURGE nuove taglie M-L-XL 200 euro<br/>
-salvagenti PALM EXTREM nuovi rosso o blu 190 euro<br/>
-paraspruzzi sandi bifoderato nuovo taglia M 83x45    75 euro<br/>
-paraspruzzi hiko tight grip taglia M 92x45 80euro<br/>
-paraspruzzi palm classic taliga L 88x50 8 euro. <br/>
<br/>
per foto scrivetemi. grazie e buone discese a tutti!! 
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6339"></a>
<div class="data">
<div style="float:left">&nbsp;nicola.paolo@email.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
Paolo Nicola
<br/>3498707880
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Giacca Palm Sidewinter Azzurra taglia L del 2011 usata 7-8 volte perchè mi va grande.<br/>
Prezzo 120 euro circa metà del prezzo di acquisto.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6338"></a>
<div class="data">
<div style="float:left">&nbsp;mattiafacci@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Messner</span><b>Vendo</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
mattia facci
<br/>3402764611
<br/>Padova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo Wavesport Habitat 80 gialla fine 2009. Buone condizioni, eventuale permuta con Zet Raptor, pagando se necessario la differenza. Su richiesta vi mando tutte le foto che volete. Euro 500 trattabili.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6337"></a>
<div class="data">
<div style="float:left">&nbsp;m.villotta@teletu.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Mauro 59</span><b>Vendo</b> annuncio del : 07/05/12</div>
</div>
<div class="estremi">
Mauro Villotta
<br/>0163827073
<br/>Novara
<br/><a href="rep/mercatino/c208474d1b199748545e854d98cec883/Vista_verticale.JPG" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/c208474d1b199748545e854d98cec883/thumb_Vista_verticale.JPG"/></a></div>
<div class="annuncio">
Vendo Rainbow "ZULU" ottime condizioni a EU. 350.<br/>
Ulteriori foto a richiesta.<br/>
Visibile in Valsesia.Info al 3478763703.<br/>
Saluti Mauro.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6336"></a>
<div class="data">
<div style="float:left">&nbsp;pieri.alessandra@fastwebnet.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: slow</span><b>Vendo</b> annuncio del : 07/05/12</div>
</div>
<div class="estremi">
luigi
<br/>3287656812
<br/>Milano
<br/><a href="rep/mercatino/93414da4af301b48885379e462702488/ShoGun.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/93414da4af301b48885379e462702488/thumb_ShoGun.jpg"/></a></div>
<div class="annuncio">
Vendo pagaia Werner Sho-Gun, offset 45°, manico ergo (bent). 320 euro. NUOVAAAA!
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6333"></a>
<div class="data">
<div style="float:left">&nbsp;bardelbenoit@yahoo.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 07/05/12</div>
</div>
<div class="estremi">
Benoit Bardel
<br/>3482212465
<br/>Aosta
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
ciao a tutti, vendo canoa “z Raptor“, di colore giallo, in buone condizioni, al prezzo di 650 euro. Per vederla potete passare a Villeneuve alla base Rafting in loc Chavonne oppure invio foto su richiesta. Mi potete chiamare al 348- 2212465 in orario pasti
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6332"></a>
<div class="data">
<div style="float:left">&nbsp;gabriele.bottazzi@hotmail.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 07/05/12</div>
</div>
<div class="estremi">
gabriele bottazzi
<br/>3398668757
<br/>Alessandria
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
VENDESI<br/>
Canoa in Polietilene molto stabile, grazie alla sua larga e piatta base di appoggio, e veloce grazie alla sua lunghezza (4.60 m). <br/>
Ottima per utilizzo in mare e lago (adatta anche per fiumi fino al II° di difficoltà), o come prima barca per neofiti e interessati ad escursioni turistiche sull’acqua piatta. <br/>
Puntapiedi a pettine, sacco di galleggiamento di coda. Colore rosa. Condizioni discrete.<br/>
<br/>
Canoa visibile e disponibile per prova presso "Il LIDO DI PREDOSA", (Predosa- AL)<br/>
<br/>
Prezzo: 170 euro <br/>
<br/>
Per ogni ulteriore chiarimento in merito o foto, non esitate a contattarmi!
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6331"></a>
<div class="data">
<div style="float:left">&nbsp;roberto.simani@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 07/05/12</div>
</div>
<div class="estremi">
robero
<br/>3474162144
<br/>Ferrara
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo tiphoon slalom Tony Prijon in polietilene colore giallo, ottime condizioni, con sacchi di punta e paraspruzzi neoprene. euro 350 consegno nelle Marche, Romagna e provincia di Ferrara.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6329"></a>
<div class="data">
<div style="float:left">&nbsp;eliagiordano1990@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Vendo</b> annuncio del : 06/05/12</div>
</div>
<div class="estremi">
elia giordano
<br/>3495011755
<br/>Cuneo
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
vendo JACKSON "STAR" arancio del 2008 usata saltuariamente a 350€... vendo causa inutilizzo problemi lavorativi e x passare a qualcosa di più voluminoso...se interessati a info e foto contattate pure
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6328"></a>
<div class="data">
<div style="float:left">&nbsp;resteno@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: sketch</span><b>Vendo</b> annuncio del : 06/05/12</div>
</div>
<div class="estremi">
stefano
<br/>
<br/>Treviso
<br/><a href="rep/mercatino/f1069a2413b24b5343611535f26eb3cd/Demon-1w.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/f1069a2413b24b5343611535f26eb3cd/thumb_Demon-1w.jpg"/></a></div>
<div class="annuncio">
Vendo per cambio modello Exo Demon arancione.<br/>
Elevate prestazioni e dimensioni compatte, concepito per torrenti di alta pendenza e grandi cascate. Stabile e veloce grazie al baricentro basso e al fondo planante. Accurato studio di linee d’acqua e distribuzione dei pesi garantiscono sicurezza e facile esecuzione dell’eskimo.<br/>
Richiesta 500 euro<br/>
Per altre foto e dettagli contattatemi via email.
</div>
</div>
</div>
<div id="panelC" class="hiddenPanel">
<span style="clear:both"><img src="img/C.jpg"></span>
<div class="contenitore_merc">
<a href="#" name="6444"></a>
<div class="data">
<div style="float:left">&nbsp;peripezia@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 24/05/12</div>
</div>
<div class="estremi">
barbara landoni
<br/>
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco kajak ad un posto rigido per fiume o lago,<br/>
sono principiante devo lasciarla sulla spiaggia e quindi vorrei spendere una cifra adeguata.<br/>
<br/>
Grazie<br/>
barbara
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6438"></a>
<div class="data">
<div style="float:left">&nbsp;uappo71@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 22/05/12</div>
</div>
<div class="estremi">
alberto pompanin
<br/>3405746533
<br/>Belluno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
cerco casco dalla sweet strutter di qualsiasi colore grazie
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6435"></a>
<div class="data">
<div style="float:left">&nbsp;kekko.87@hotmail.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
Francesco
<br/>3338657902
<br/>Siena
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco casco WRS EAGLE o SWEET ROCKER o SWEET STRUTTER<br/>
<br/>
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6434"></a>
<div class="data">
<div style="float:left">&nbsp;fulvio.guarino@unicredit.eu </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
fulvio guarino
<br/>3931860152
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
cerco canoa FLUID mod. DETOX taglia m.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6433"></a>
<div class="data">
<div style="float:left">&nbsp;fulvio.guarino@unicredit.eu </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
fulvio guarino
<br/>3931860152
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
cerco canoa BIG DOG mod. FLUX 7.7
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6428"></a>
<div class="data">
<div style="float:left">&nbsp;uappo71@alice.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 21/05/12</div>
</div>
<div class="estremi">
Alberto pompanin
<br/>3405746533
<br/>Belluno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco kayak da gioco taglia media a modico prezzo grazie
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6415"></a>
<div class="data">
<div style="float:left">&nbsp;andreak92@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 19/05/12</div>
</div>
<div class="estremi">
andrea martini
<br/>
<br/>Verona
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
cerco canoa da rodeo lunga meno di 2 metri. Massimo 300/350 euro.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6407"></a>
<div class="data">
<div style="float:left">&nbsp;vertebrato@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 17/05/12</div>
</div>
<div class="estremi">
renzo monelli
<br/>3357774404
<br/>Mantova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco idra o gangster blu, nera, gialla, rossa.<br/>
Grazie
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6406"></a>
<div class="data">
<div style="float:left">&nbsp; </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 17/05/12</div>
</div>
<div class="estremi">
Daniele
<br/>3473809809
<br/>Venezia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco K2 olimpico buone condizioni.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6401"></a>
<div class="data">
<div style="float:left">&nbsp;ufficio@progavirate.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 16/05/12</div>
</div>
<div class="estremi">
claudio master
<br/>
<br/>Varese
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco canoa canadese in vetroresina.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6400"></a>
<div class="data">
<div style="float:left">&nbsp;andrea.mantovani@intesasanpaolo.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 16/05/12</div>
</div>
<div class="estremi">
Andrea Mantovani
<br/>3384288107
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco kayak rigido 2 posti in buono stato (utilizzo lago).
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6394"></a>
<div class="data">
<div style="float:left">&nbsp;fabiomata@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Mata</span><b>Compro</b> annuncio del : 15/05/12</div>
</div>
<div class="estremi">
Fabio
<br/>3474879421
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco casco WRSI Current con mentoniera.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6376"></a>
<div class="data">
<div style="float:left">&nbsp;lucamongu@msn.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
Luca Monguzzi
<br/>
<br/>Milano
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco kayak sit on top usato per piccole escursioni lago mare e per pescare sottocosta...<br/>
Budget 350€
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6374"></a>
<div class="data">
<div style="float:left">&nbsp;dj-dany@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
Daniele Bergamelli
<br/>3200
<br/>Bergamo
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
ciao a tutti ceerco pyranha ammo ciao grazie Daniele
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6369"></a>
<div class="data">
<div style="float:left">&nbsp;luca.yak@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 13/05/12</div>
</div>
<div class="estremi">
luca bruschi
<br/>3334274538
<br/>Lecco
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco BURN S...tutto qui...
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6364"></a>
<div class="data">
<div style="float:left">&nbsp;domagos@hotmail.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 11/05/12</div>
</div>
<div class="estremi">
Domenico Agostini
<br/>3282258671
<br/>Livorno
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco paraspruzzi per pozzetto 79x46 taglia in vita large e abbigliamento vario taglia xl.
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6360"></a>
<div class="data">
<div style="float:left">&nbsp;vertebrato@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 11/05/12</div>
</div>
<div class="estremi">
renzo monelli
<br/>3357774404
<br/>Mantova
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco Mafia, Gangster, Idra blu.<br/>
Grazie,<br/>
Renzo
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6351"></a>
<div class="data">
<div style="float:left">&nbsp;dj-dany@libero.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
Daniele Bergamelli
<br/>3200962669
<br/>Bergamo
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
cerco casco sweet cocker taglia l\xl nero o verde ciao Daniele
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6343"></a>
<div class="data">
<div style="float:left">&nbsp; </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
Giacomo
<br/>330987712
<br/>Cosenza
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco canoa da mare chiusa affusolata max 600€
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6342"></a>
<div class="data">
<div style="float:left">&nbsp;hall7@tiscali.it </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 08/05/12</div>
</div>
<div class="estremi">
alessandro borsoi
<br/>3932414354
<br/>Venezia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Cerco pagaia jantex o bracsa 4' per gare sprint e velocità.(da 200 a 2000 MT ).
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6330"></a>
<div class="data">
<div style="float:left">&nbsp; </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Compro</b> annuncio del : 06/05/12</div>
</div>
<div class="estremi">
raffaella
<br/>
<br/>Bologna
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
cerco canoa wave diesel 60 in buono stato
</div>
</div>
</div>
<div id="panelA" class="hiddenPanel">
<span style="clear:both"><img src="img/A.jpg"></span>
</span>
<div class="contenitore_merc">
<a href="#" name="6408"></a>
<div class="data">
<div style="float:left">&nbsp;andrea.gangemi@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: Gange</span><b>Varie</b> annuncio del : 17/05/12</div>
</div>
<div class="estremi">
Andrea Gangemi
<br/>340 5987091
<br/>Nuoro
<br/><a href="rep/mercatino/6c1b738a9c84dca9a8640e91bd9b2684/CasaGangemi01.jpg" rel="thumbnail"><img style="border:0" alt="foto kayak usato" src="rep/mercatino/6c1b738a9c84dca9a8640e91bd9b2684/thumb_CasaGangemi01.jpg"/></a></div>
<div class="annuncio">
Monolocale 45mq diviso in due aree con ampio (enorme) giardino, posto auto coperto, barbecue e cisterna autonoma.<br/>
Situato a Montepetrosu (NU) tra Porto S. Paolo e San Teodoro, in piena Area Marina Protetta di Tavolara e Molara.<br/>
Un bel posto per fare kayak marino e immersioni<br/>
<br/>
link alla mappa:<br/>
http://g.co/maps/9r8v6<br/>
<br/>
foto dell'esterno:<br/>
https://plus.google.com/photos/107709750212733306448/albums/5176899543441382209
</div>
</div>
<div class="contenitore_merc">
<a href="#" name="6399"></a>
<div class="data">
<div style="float:left">&nbsp;cescohs@gmail.com </div>
<div style="text-align:right"><span style="font-size:9px;padding-right:10px">posted by: anonimo</span><b>Varie</b> annuncio del : 16/05/12</div>
</div>
<div class="estremi">
Francesco Pietrantoni
<br/>3477408734
<br/>La Spezia
<br/><img src="rep/mercatino/nofoto.gif" alt="nofoto"/></div>
<div class="annuncio">
Vendo <br/>
mitico furgone autocarro Hyundai H1tdi 2500<br/>
passo lungo del 2001<br/>
a soli 3000 €- Super tagliandato – no problemi meccanici<br/>
- Attrezzato con pianale posteriore in legno a botole<br/>
ottimo per lavoro – campeggio – sport<br/>
- Portapacchi a tre barre<br/>
Predisposizioni elettriche per impianto fotovoltaico e utenze interne a 12Volt<br/>
Botola areazione vasistas/zanzariera vano post.<br/>
Ruota di scorta 1 pneumatico nuovo omaggio<br/>
Impianto stereo 2 casse a 2 vie 2 twitter<br/>
Riverniciato recentemente<br/>
</div>
</div>
</div>
</div>
<script type="text/javascript" src="js/thumb.js.pagespeed.jm.gswOHuVMz4.js"></script>
<!-- END  CONTENTS -->
</form>
</div>
</td>
<td class="dxCol">
<!-- INIZIO MENU DX -->
<div class="rettangolo" style="text-align:justify">
<div class="rettangolo_titolo" style="">come funziona</div>
<div class="mini_contenuti">
<div class="mini_testo_link">
Per inserire un annuncio di compravendita non occorre essere registrati
</div>
<div class="mini_testo_link">
I campi contrassegnati da asterisco sono obbligatori
gli altri sono facoltativi anche se per vendere
qualcosa il telefono dell'inserzionista e la foto dell'oggetto
possono aiutare molto.
</div>
<div class="mini_testo_link">
L'<u>annuncio</u>, sottoposto all' approvazione dei moderatori,
<u>ha la durata di 21 giorni</u>, trascorsi i quali viene cancellato.
l'inserzionista dovrà inviarlo nuovamente se ne ha ancora interesse
</div>
<div class="mini_testo_link">
CKFiumi non e' responsabile degli annunci pubblicati
ma solo un tramite per transazioni tra privati
</div>
</div>
<div id="main_link"></div>
</div>
<div class="rettangolo" style="text-align:center;padding: 10px 2px 10px 2px">
<p style="font-size:18px">
DURATA ANNUNCIO: <br/><h1>21 GIORNI !</h1>
</p>
</div>
<div class="rettangolo" style="text-align:center;padding: 10px 2px 10px 2px">
TRUFFE ONLINE: <br/>Invitiamo a fare attenzione diffidando dei contatti via mail
scritti con italiano scarso o in inglese (scarso pure quello).<br/>
La comunita' dei canoisti nostrana e' ben piccola per cui e' facile accertarsi dell'
identita' del vostro interlocutore.<br/>
</div>
<!-- FINE MENU DX -->
<br/><br/>
<div class="rettangolo" style="text-align:center;padding: 10px 2px 10px 2px">
<script type="text/javascript">google_ad_client="pub-9030582154887701";google_ad_slot="2639195637";google_ad_width=120;google_ad_height=600;</script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
<script type="text/javascript">google_ad_client="pub-9030582154887701";google_ad_slot="2766649753";google_ad_width=120;google_ad_height=600;</script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
<script type="text/javascript">google_ad_client="pub-9030582154887701";google_ad_slot="5284196569";google_ad_width=120;google_ad_height=600;</script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
<script type="text/javascript">google_ad_client="pub-9030582154887701";google_ad_slot="0252271262";google_ad_width=120;google_ad_height=600;</script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
</div>
</td>
</tr>
</table>
</div>
<!-- END MAIN AREA -->
<!-- INIZIO FOOTER -->
<div id="footer">
<p><a href="/">home</a> &#8226;
<a href="fiume.phtml">fiumi</a> &#8226;
<a href="ricerca.phtml">ricerca fiumi</a> &#8226;
<a href="help.phtml">come funziona</a> &#8226;
<a href="gradi.phtml">I gradi WW</a> &#8226;
<a href="contatto.phtml">scrivici</a> &#8226;
<a href="profilo.phtml/dani">webmaster</a>
</p>
<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o
pubblicazione anche parziale per fini commerciali<br/>
</p>
<p class="loghi"><a href="redirect.phtml?target=fick" rel="nofollow"><img src="img/sponsor/logo_fick_micro.jpg.pagespeed.ce.gXOIyL-4rP.jpg" style="border:0px" alt="FICK"/></a>
&nbsp;<a href="redirect.phtml?target=fict" rel="nofollow"><img src="img/sponsor/logo_fict_micro.jpg.pagespeed.ce.yEain7cY8r.jpg" style="border:0px" alt="FICT"/></a>
&nbsp;<a href="redirect.phtml?target=uisp" rel="nofollow"><img src="img/sponsor/logo_uisp_micro.jpg.pagespeed.ce.TqlS86I2Jb.jpg" style="border:0px" alt="UISP"/></a>
</p>
</div>
</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">_uacct="UA-666569-2";urchinTracker();</script>
</body>
</html>
