






<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Ckfiumi :: gli Iscritti! </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa," />
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..." />
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0=" />
<link href="http://kstatic.ckfiumi.net/css/defaults.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://kstatic.ckfiumi.net/js/all-1.js"></script>
<script type="text/javascript">
if(top.location != location) {
   top.location.href = document.location.href;
}
</script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
	<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
	<div id="mainFront">
	  	<img id="a" src="http://kstatic.ckfiumi.net/img/header/33.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
	</div>
    <div id="containerMenu"><div
   		 id="menu_left"><img src="http://kstatic.ckfiumi.net/img/sfondo_barra_sx.gif"  alt="" /></div><div
		  id="menu_right"><img src="http://kstatic.ckfiumi.net/img/sfondo_barra_dx.gif"  alt="" /></div><div
		  id="menu_orizz">
			<a  class="menu" href="/">Home</a> |
			<a  class="menu" href="/fiume.phtml">Fiumi</a> |
			<a  class="menu" href="/news/calendario.phtml">Appuntamenti</a> |
			<a  class="menu" href="/mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
			<a  class="menu_selected_U" href="http://forum.ckfiumi.net">Forums CKI</a> |
			<a  class="menu" href="/racconti.phtml">Vita di Fiume</a> |
			<a  class="menu" href="/contatto.phtml">Scrivici</a> |
			<a  class="menu" href="/login.phtml">Login</a> |
		</div>
	</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->	



	<!-- BEGIN MAIN AREA -->
	<div id="main">
		<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
      	<tr>
        	<td class="sxCol">
			<div id="elCont">
				<div id="elCont_left" class="z_listaEditor"></div><div
		  		id="elCont_right">I nostri editori</div>
			</div>
			<div id="sottoElCont">	
				<form id="LOC" action="/show.phtml" method="post">
				<!-- BEGIN  CONTENTS -->
				<div style="padding:10px;text-align:center;border: 1px solid black">
<!-- inizio form ricerca -->
<div>
<div style="float:left">ricerca per alias <input type="text" value="" name="Alias"/></div>
<div style="float:right">ricerca per email <input type="text" value="" name="Email"/></div>
</div><br/><br/>
<div style=""><input class="bottone" type="submit" name="go" value="ricerca" /></div>
<!-- fine form ricerca -->
</div>
<div class="small">l' icona <img src="/img/profilo.gif" style="width:14px"/> indica se l'editore ha inserito un profilo</div>
<br/>
<div style="padding-top:20px">
<table cellpadding="0" cellspacing="0" border="0" style="width:100%">
	
	<tr>
		<td><a href="/profilo.phtml/16mm"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/16mm">16mm</a></td>
		<td class="capitalizza">enrico</td>
		<td class="capitalizza">comaschi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/66lucablu"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/66lucablu">66lucablu</a></td>
		<td class="capitalizza">luca</td>
		<td class="capitalizza">raspanti</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/AAAlbi"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/AAAlbi">AAAlbi</a></td>
		<td class="capitalizza">Alberto</td>
		<td class="capitalizza">Floridi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Acqua Santa"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Acqua Santa">Acqua Santa</a></td>
		<td class="capitalizza">Pippo</td>
		<td class="capitalizza">Spano</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/adelchi"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/adelchi">adelchi</a></td>
		<td class="capitalizza">massimo</td>
		<td class="capitalizza">longhi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Afofix"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Afofix">Afofix</a></td>
		<td class="capitalizza">Alex</td>
		<td class="capitalizza">Spallarossa</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/afrikaners"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/afrikaners">afrikaners</a></td>
		<td class="capitalizza">paolo</td>
		<td class="capitalizza">di quattro</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/aky"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/aky">aky</a></td>
		<td class="capitalizza">achille</td>
		<td class="capitalizza">grassi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alba"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alba">alba</a></td>
		<td class="capitalizza">maurizio</td>
		<td class="capitalizza">albanese</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/albe61turbigo"><img src="/img/profilo.gif" style="border:none" alt="vedi profilo" title="vedi profilo"/></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/albe61turbigo">albe61turbigo</a></td>
		<td class="capitalizza">alberto</td>
		<td class="capitalizza">bianchi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Alberto"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Alberto">Alberto</a></td>
		<td class="capitalizza">Alberto</td>
		<td class="capitalizza">Garzena</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Alberto Antonini"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Alberto Antonini">Alberto Antonini</a></td>
		<td class="capitalizza">alberto</td>
		<td class="capitalizza">antonini</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Alberto Santi"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Alberto Santi">Alberto Santi</a></td>
		<td class="capitalizza">Alberto</td>
		<td class="capitalizza">Santi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alberto sottocosta"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alberto sottocosta">alberto sottocosta</a></td>
		<td class="capitalizza">alberto</td>
		<td class="capitalizza">ruggieri</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alberto78"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alberto78">alberto78</a></td>
		<td class="capitalizza">alberto</td>
		<td class="capitalizza">avitabile</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alberto84"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alberto84">alberto84</a></td>
		<td class="capitalizza">Alberto</td>
		<td class="capitalizza">Ferro</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/AlbertONE"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/AlbertONE">AlbertONE</a></td>
		<td class="capitalizza">Alberto</td>
		<td class="capitalizza">Ciocci</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/albycfm"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/albycfm">albycfm</a></td>
		<td class="capitalizza">alberto</td>
		<td class="capitalizza">cereda</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/ale"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/ale">ale</a></td>
		<td class="capitalizza">ale </td>
		<td class="capitalizza">villa</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alejo"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alejo">alejo</a></td>
		<td class="capitalizza">alejandro</td>
		<td class="capitalizza">devalle</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/AlessandroCFM"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/AlessandroCFM">AlessandroCFM</a></td>
		<td class="capitalizza">Alessandro</td>
		<td class="capitalizza">Gentili</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alessio"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alessio">alessio</a></td>
		<td class="capitalizza">alessio</td>
		<td class="capitalizza">cannizzo</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alevilla"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alevilla">alevilla</a></td>
		<td class="capitalizza">Ale</td>
		<td class="capitalizza">villa </td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Alex"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Alex">Alex</a></td>
		<td class="capitalizza">Alex</td>
		<td class="capitalizza">Pellegrini </td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Alexdemels"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Alexdemels">Alexdemels</a></td>
		<td class="capitalizza">Alessandro</td>
		<td class="capitalizza">Cazzaniga</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alfascheggia"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alfascheggia">alfascheggia</a></td>
		<td class="capitalizza">Matteo</td>
		<td class="capitalizza">Franchi</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alfpaddle"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alfpaddle">alfpaddle</a></td>
		<td class="capitalizza">paolo</td>
		<td class="capitalizza">busacca</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alias"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alias">alias</a></td>
		<td class="capitalizza">Giuseppe</td>
		<td class="capitalizza">Ottria</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alice"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alice">alice</a></td>
		<td class="capitalizza">alice</td>
		<td class="capitalizza">prete</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Alpe"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Alpe">Alpe</a></td>
		<td class="capitalizza">alessandro</td>
		<td class="capitalizza">perini</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alvins"><img src="/img/profilo.gif" style="border:none" alt="vedi profilo" title="vedi profilo"/></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alvins">alvins</a></td>
		<td class="capitalizza">alberto</td>
		<td class="capitalizza">crivellari</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/alx"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/alx">alx</a></td>
		<td class="capitalizza">alessio</td>
		<td class="capitalizza">pizzuto</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/amattioli"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/amattioli">amattioli</a></td>
		<td class="capitalizza">armando</td>
		<td class="capitalizza">mattioli</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/andrea"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/andrea">andrea</a></td>
		<td class="capitalizza">andrea</td>
		<td class="capitalizza">contini</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/andrea l"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/andrea l">andrea l</a></td>
		<td class="capitalizza">Andrea</td>
		<td class="capitalizza">Lovato </td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/andrea parenti"><img src="/img/profilo.gif" style="border:none" alt="vedi profilo" title="vedi profilo"/></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/andrea parenti">andrea parenti</a></td>
		<td class="capitalizza">andrea</td>
		<td class="capitalizza">parenti</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Andrea Ravagnan"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Andrea Ravagnan">Andrea Ravagnan</a></td>
		<td class="capitalizza">andrea</td>
		<td class="capitalizza">ravagnan</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Andrea87"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Andrea87">Andrea87</a></td>
		<td class="capitalizza">Andrea</td>
		<td class="capitalizza">Contini</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/Andrea90"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/Andrea90">Andrea90</a></td>
		<td class="capitalizza">Andrea</td>
		<td class="capitalizza">Pontone</td>
	</tr>
	
	<tr>
		<td><a href="/profilo.phtml/andrea93"></a></td>
		<td class="capitalizza"><a href="/profilo.phtml/andrea93">andrea93</a></td>
		<td class="capitalizza">andrea </td>
		<td class="capitalizza">granini</td>
	</tr>
	
</table>
</div>
<div style="height:10" colspan="5">&nbsp;</div>
</div>
   			<div style="text-align:center">
   			&nbsp;
   			
   			<b>1</b>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=2">2</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=3">3</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=4">4</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=5">5</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=6">6</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=7">7</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=8">8</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=9">9</a>
   			
   			&nbsp;
   			<a class="next" href="/show.phtml?pagenum=10">&nbsp;<b>Next</b></a>
   			
   			&nbsp;
   			<br/>
   			<i>(20 pagine totali )</i>
   			</div>
<br/><br/>			
   

				<!-- END  CONTENTS -->
				</form>
			</div>
			</td>
        	<td class="dxCol">
				<!-- INIZIO MENU DX -->
			<div id="menudx">
			<ul>
				<li class="menu"><a href="/login.phtml">Login</a></li>
				<li class="menu"><a href="/registra.phtml">Registrati</a></li>
				<li class="menu"><a href="/recupera.phtml">Recupera Password</a></li>
				<li class="menu"><a href="/help.phtml">Come Funziona</a></li>
				<li class="menu"><a href="/madeby.phtml">Chi siamo</a></li>
				<li class="submenu_selected_U"><a href="/show.phtml">Lista Editori</a></li>
			</ul>
			</div>
			<div class="textWel">
		 	 <a href="/registra.phtml">Diventa anche tu un editore!</a>
		  	</div>	
			<div class="textWel">
			<p>TI RICORDIAMO CHE:<br/>
			1- I fiumi vanno discesi con  attrezzature e abbigliamento  adatto al tipo di percorso 
			affrontato.<br/> 
			2- Per discendere i fiumi bisogna frequentare dei corsi di canoa tenuti da 
			personale qualificato.<br/> 
			3- I principianti durante le discese devono essere affiancati e consigliati 
			da guide esperte.<br/>
			4- Una discesa non si effettua mai in solitaria, il numero minimo dei partecipanti può variare 
			a seconda della preparazione dei canoisti e delle difficoltà che si possono incontrare.
			</p>
			</div>
<!-- FINE MENU DX -->		

			</td>
      	</tr>
    	</table>
	</div>
	<!-- END MAIN AREA -->
		<!-- INIZIO FOOTER -->
		<div id="footer">
		      <p><a href="/">home</a> &#8226;  
			  <a href="/fiume.phtml">fiumi</a> &#8226; 
			  <a href="/ricerca.phtml">ricerca fiumi</a> &#8226;
			  <a href="/help.phtml">come funziona</a>  &#8226;
			  <a href="/gradi.phtml">I gradi WW</a> &#8226; 
			  <a href="/contatto.phtml">scrivici</a> &#8226; 
			  <a href="/profilo.phtml/dani">webmaster</a>  
			  </p>
				<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o 
			pubblicazione  anche parziale per fini commerciali<br/>
			</p>
	<p class="loghi"><a href="/redirect.phtml?target=fick" rel="nofollow"><img src="http://kstatic2.ckfiumi.net/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="http://kstatic.ckfiumi.net/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="http://kstatic2.ckfiumi.net/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	</p>
		</div>
	</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-666569-2";
urchinTracker();
</script>
</body>
</html>






