<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Ckfiumi :: lettore Rss and NewsGroup </title>
<meta name="keywords" content="Guida fluviale, fiumi, torrenti, descrizione fiumi, canoa, kayak, discesa in canoa,"/>
<meta name="description" content="Guida ai fiumi italiani per la discesa in canoa o in kayak. Informazioni e descrizione sul percorso, il livello di difficoltà, i pericoli da evitare, l'imbarco, lo sbarco..."/>
<meta name="verify-v1" content="WZLlJNeLkSySoGsfzZKbP91b+MogLp2Um8SNjdqX+m0="/>
<link href="/css/A.defaults.css.pagespeed.cf.fmQPojuK-r.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="/js/all-1.js.pagespeed.jm.oQxXBlF1gD.js"></script>
<script type="text/javascript">if(top.location!=location){top.location.href=document.location.href;}</script>
<!--<script type="text/javascript" src="/js/lightbox2.js"></script>	-->
</head>
<body onload="initDynamicOptionLists();">
<div id="container">
<div id="header">
<!--	<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg" style="border:0px" alt="FICK"/></a>
	&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg" style="border:0px" alt="FICT"/></a>
	&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg" style="border:0px" alt="UISP"/></a>
	&nbsp;<a href="http://forum.ckfiumi.net"><img src="/img/cki_logo.gif" alt="logo CKI" style="border:none" /></a>
-->	</div>
<div id="mainFront">
<img id="a" src="/img/header/24.jpg" alt="immagine principale" width="732" height="102" style="vertical-align : middle;"/>
</div>
<div id="containerMenu"><div id="menu_left"><img src="/img/xsfondo_barra_sx.gif.pagespeed.ic.pDJxMOJcbI.png" alt=""/></div><div id="menu_right"><img src="/img/xsfondo_barra_dx.gif.pagespeed.ic.5a2WR5Ag1k.png" alt=""/></div><div id="menu_orizz">
<a class="menu" href="/">Home</a> |
<a class="menu" href="/fiume.phtml">Fiumi</a> |
<a class="menu_selected_U" href="calendario.phtml">Appuntamenti</a> |
<a class="menu" href="/mercatino_canoa_kayak_usati.phtml">Mercatino</a> |
<a class="menu" href="http://forum.ckfiumi.net">Forums CKI</a> |
<a class="menu" href="/racconti.phtml">Vita di Fiume</a> |
<a class="menu" href="/contatto.phtml">Scrivici</a> |
<a class="menu" href="/login.phtml">Login</a> |
</div>
</div> <!-- chiude div_containerMenu -->
<!-- FINE HEADER -->
<!-- BEGIN MAIN AREA -->
<div id="main">
<table cellpadding="0" cellspacing="0" class="zeTabo" border="1">
<tr>
<td class="sxCol">
<div id="elCont_empty">
</div>
<div id="sottoElCont">
<form id="LOC" action="/news/rss.phtml" method="post">
<!-- BEGIN  CONTENTS -->
<div style="text-align:right">
<div class="rss_channel" style="padding:8px;background-color:#EAEBEE;text-align:right;border:none"><b>seleziona un Newsgroup di:</b>
<select name="rss" style="width:220px" onchange="document.getElementById('LOC').submit()">
<option value="cki">CKI old</option>
<option value="cki_new" selected="selected">CKI next generation</option>
<option value="cki_db_news">Editori di CKFiumi</option>
<option value="ccn">Canoa Club Novara</option>
<option value="cfm">Canoa Fluviale Martesana</option>
<option value="pagaiarosa">Pagaia Rosa</option>
<option value="playak_press">Playak.com - press</option>
<option value="playak_kayaks">Playak.com - kayaks</option>
<option value="yahoo_news">Yahoo kayak news</option>
</select>
</div>
<br/>
<b><a href="http://forum.ckfiumi.net/index.php">Canoa Kayak Italia - CKI dal 1998 il forum della canoa italiana</a></b><br/>&nbsp;
<div class="rss_item">
<span style="font-size:x-small">0 ora fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3952.msg14855.html#msg14855" onclick="window.open(this.href,'CKI');return false;">Re: Trasimeno</a>
<br>
allora settembre è arrivato d è tempo di fare programmi.<br/>io i prossimi due we sono al lago. Sabato e domenica (8/9) il meteo da bel tempo e c&#39;è da provare il kayak nuovo di Fràa. Quindi direi che sto&#39; in acqua sia sabato che domenica tutto il giorno (c...
</div>
<div class="rss_item">
<span style="font-size:x-small">2 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4049.msg14854.html#msg14854" onclick="window.open(this.href,'CKI');return false;">Un'interessante regione fluviale in Austria</a>
<br>Ciao a tutti e un augurio di una stagione canoistica autunnale intensa! Mi era caro segnalare agli appassionati una zona austriaca nella quale mi sono recato gli ultimi giorni di agosto, da solo, confidando nelle previsioni metereologiche per i livelli...
</div>
<div class="rss_item">
<span style="font-size:x-small">2 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3975.msg14853.html#msg14853" onclick="window.open(this.href,'CKI');return false;">Re: Idrometri Piemonte</a>
<br>Vuol dire che l&#39;argomento viene elencato tra i primi in alto, ovvero tra quelli più recenti, e quindi viene più facilmente trovato e letto dagli utenti.
</div>
<div class="rss_item">
<span style="font-size:x-small">3 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3975.msg14852.html#msg14852" onclick="window.open(this.href,'CKI');return false;">Re: Idrometri Piemonte</a>
<br>cosa vuol dire spostiamo in alto ?
</div>
<div class="rss_item">
<span style="font-size:x-small">4 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3975.msg14851.html#msg14851" onclick="window.open(this.href,'CKI');return false;">Re: Idrometri Piemonte</a>
<br>
Spostiamo in alto questa discussione, perchè è importante avere i link per l&#39;idrometro di Campertogno in questi giorni di nuove precipitazioni.<br/>Ieri Sesia tratto di gara e Sermenza con livelli non alti, ma accettabili per scendere e divertirsi.<br/>Ciao,<br/><br/>Ste
</div>
<div class="rss_item">
<span style="font-size:x-small">4 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4048.msg14850.html#msg14850" onclick="window.open(this.href,'CKI');return false;">Re: Un breve viaggio in canoa nel Giura Francese</a>
<br>Bella descrizione Tojo. Sono contento che tu sia ritornato ad esplorare luoghi poco frequentati dai canoisti italiani. A presto in Liguria: sta piovendo forte ora!Ciao
</div>
<div class="rss_item">
<span style="font-size:x-small">5 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4048.msg14849.html#msg14849" onclick="window.open(this.href,'CKI');return false;">Re: Un breve viaggio in canoa nel Giura Francese</a>
<br>Ecco, così mi piaci&nbsp; <img src="http://forum.ckfiumi.net/Smileys/default/smiley.gif" alt="Sorriso" border="0"/>, bel reportage Toio, Grazie.&nbsp; <img src="http://forum.ckfiumi.net/Smileys/default/wink.gif" alt="Occhiolino" border="0"/>
</div>
<div class="rss_item">
<span style="font-size:x-small">20 ore fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3901.msg14848.html#msg14848" onclick="window.open(this.href,'CKI');return false;">Re: COPPA DEL MONDO SLALOM 2012</a>
<br>Cala il sipario sulla Coppa del Mondo di Slalom 2012 e quasi sembra prenderci impreparati. In un attimo si chiude un capitolo lungo cinque mesi che ha coinvolto 412 atleti in rappresentanza di 38 nazioni di tutti e 5 i continenti. Ha toccato 5 diverse ...
</div>
<div class="rss_item">
<span style="font-size:x-small">1 giorno fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4048.msg14847.html#msg14847" onclick="window.open(this.href,'CKI');return false;">Un breve viaggio in canoa nel Giura Francese</a>
<br>Quando,&nbsp; nei decenni passati e prima dellavvento di Internet, il Canoa Club Milano era un punto di riferimento per la canoa italiana, arrivavano da Francia, Germania e da tuttEuropa inviti a partecipare a manifestazioni canoistiche. Ero un ragazzo e ...
</div>
<div class="rss_item">
<span style="font-size:x-small">1 giorno fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4037.msg14846.html#msg14846" onclick="window.open(this.href,'CKI');return false;">Re: Ciao a tutti e consiglio: Sevylor o ZPro?</a>
<br>
Ciao siccome sono interessato alla discussione,la seguo piu&#39; che volentieri.<br/>Ciao e grazie <br/>Angelo
</div>
<div class="rss_item">
<span style="font-size:x-small">1 giorno fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3901.msg14845.html#msg14845" onclick="window.open(this.href,'CKI');return false;">Re: COPPA DEL MONDO SLALOM 2012</a>
<br>Siamo tornati a fare e a parlare di slalom grazie ad un percorso che almeno fino alla porta 16 ha una sua logica, peccato solo per le ultime tre porte che mettono in seria difficoltà le canadesi, pregiudicandone la scorrevolezza e la fluidità dazione....
</div>
<div class="rss_item">
<span style="font-size:x-small">2 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3901.msg14844.html#msg14844" onclick="window.open(this.href,'CKI');return false;">Re: COPPA DEL MONDO SLALOM 2012</a>
<br>Il cielo è tornato bigio e questa mattina la sveglia è stata la pioggia sulla mia casa viaggiante. Poi la giornata è corsa via veloce come il vento che ha disturbato le gare di qualifica. Gare... se si può parlare di gare o semplicemente sono state una...
</div>
<div class="rss_item">
<span style="font-size:x-small">2 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4046.msg14843.html#msg14843" onclick="window.open(this.href,'CKI');return false;">Re: Sabaudia-Sperlonga: un po' particolare</a>
<br>
Bravo Andrea, hai fatto un sacco di cose interessanti quest&#39;estate.<br/>Complimenti
</div>
<div class="rss_item">
<span style="font-size:x-small">3 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4046.msg14842.html#msg14842" onclick="window.open(this.href,'CKI');return false;">Re: Sabaudia-Sperlonga: un po' particolare</a>
<br>Complimenti, queste mini avventure mi attirano molto, anche perchè prima o poi anche io voglio farmi appunto un bel giro in kayak con almeno un pausa notturna in spiaggia. Diciamo che per me sarebbe un inizio per valutare vari fattori e circostanze, pr...
</div>
<div class="rss_item">
<span style="font-size:x-small">3 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4047.msg14841.html#msg14841" onclick="window.open(this.href,'CKI');return false;">consiglio acquisto</a>
<br>Ciao a tutti, sono appena tornato dal SOCA&#39; (sig)&nbsp; abbiamo fatto molte discese con il nostro raft, ci siamo divertiti, ma quello che ho visto fare dai kayak mi ha convinto di acquistarne uno vorrei un consiglio su quale prendere, premesso che vorrei co...
</div>
<div class="rss_item">
<span style="font-size:x-small">3 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4046.msg14840.html#msg14840" onclick="window.open(this.href,'CKI');return false;">Re: Sabaudia-Sperlonga: un po' particolare</a>
<br>
Esperienza un po&#39; minimalista per i miei gusti però dev&#39;essere stata bella .. e appunto innovativa.. :-)<br/>Mi piace soprattutto l&#39;idea, portata in questo caso all&#39;estremo, che il mezzo è solo il mezzo, quello che conta davvero è ciò che ci circonda.<br/><br/>Il c...
</div>
<div class="rss_item">
<span style="font-size:x-small">3 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4046.msg14839.html#msg14839" onclick="window.open(this.href,'CKI');return false;">Sabaudia-Sperlonga: un po' particolare</a>
<br>Da qualche mese carezzavo l&#39;idea di riuscire a fare campeggio nautico con la tavola da stand up paddling; da qualche settimana di riuscire a farlo con mio figlio Luca di 8 anni, già da qualche anno con me alla Discesa del Tevere e da questa estate appa...
</div>
<div class="rss_item">
<span style="font-size:x-small">3 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,3901.msg14838.html#msg14838" onclick="window.open(this.href,'CKI');return false;">Re: COPPA DEL MONDO SLALOM 2012</a>
<br>Siamo arrivati alla scena madre della Coppa del Mondo Slalom 2012: il gran finale di Bratislava Repubblica Slovacca e le premesse per un atto conclusivo fantasmagorico ci potevano stare tutte. Stanno montando stand di ogni genere per arredare unarea c...
</div>
<div class="rss_item">
<span style="font-size:x-small">3 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,114.msg14837.html#msg14837" onclick="window.open(this.href,'CKI');return false;">Re: Segnaliamo le Webcam che inquadrano Fiumi.</a>
<br>
Sotto il Ponte di Piode sul Sesia : <a href="http://www.meteoindiretta.it/scheda_webcam.php?id_webcam=10103" target="_blank">http://www.meteoindiretta.it/scheda_webcam.php?id_webcam=10103</a><br/><br/>Fred
</div>
<div class="rss_item">
<span style="font-size:x-small">4 giorni fa</span> &nbsp; <a href="http://forum.ckfiumi.net/index.php/topic,4045.msg14836.html#msg14836" onclick="window.open(this.href,'CKI');return false;">Re: Consiglio per acquisto (Janautica Seal?)</a>
<br>ciao, stai attento alla misura del pozzetto... io col victoria della janautica sono stretto e scomodo.. ovviamente dipende dalla tua altezza / corporatura se sei come me 1.85 per 87kg provalo prima...
</div>
</div>
<!-- END  CONTENTS -->
</form>
</div>
</td>
<td class="dxCol">
<!-- INIZIO MENU DX -->
<div id="menudx">
<ul>
<li class="menu"><a href="calendario.phtml">Calendario</a></li>
<li class="submenu_selected_U"><a <a href="rss.phtml">Consulta i Forum (rss)</a></li>
</ul>
</div>
<div class="textWel">
<a href="/registra.phtml">Diventa anche tu un editore!</a>
</div>
<div class="textWel">
<p>TI RICORDIAMO CHE:<br/>
1- I fiumi vanno discesi con attrezzature e abbigliamento adatto al tipo di percorso
affrontato.<br/>
2- Per discendere i fiumi bisogna frequentare dei corsi di canoa tenuti da
personale qualificato.<br/>
3- I principianti durante le discese devono essere affiancati e consigliati
da guide esperte.<br/>
4- Una discesa non si effettua mai in solitaria, il numero minimo dei partecipanti può variare
a seconda della preparazione dei canoisti e delle difficoltà che si possono incontrare.
</p>
</div>
<!-- FINE MENU DX -->
</td>
</tr>
</table>
</div>
<!-- END MAIN AREA -->
<!-- INIZIO FOOTER -->
<div id="footer">
<p><a href="/">home</a> &#8226;
<a href="/fiume.phtml">fiumi</a> &#8226;
<a href="/ricerca.phtml">ricerca fiumi</a> &#8226;
<a href="/help.phtml">come funziona</a> &#8226;
<a href="/gradi.phtml">I gradi WW</a> &#8226;
<a href="/contatto.phtml">scrivici</a> &#8226;
<a href="/profilo.phtml/dani">webmaster</a>
</p>
<p>&copy; 2006 Le informazioni e i consigli forniti in questa guida, sono redatte da canoisti volontari se ne vieta pertanto la duplicazione, riproduzione o
pubblicazione anche parziale per fini commerciali<br/>
</p>
<p class="loghi"><a href="/redirect.phtml?target=firaft" rel="nofollow"><img src="/img/sponsor/xfiraft.jpg.pagespeed.ic.7L4NqbLtIC.jpg" style="border:0px" alt="FIRAFT"/></a>
&nbsp;<a href="/redirect.phtml?target=fick" rel="nofollow"><img src="/img/sponsor/logo_fick_micro.jpg.pagespeed.ce.gXOIyL-4rP.jpg" style="border:0px" alt="FICK"/></a>
&nbsp;<a href="/redirect.phtml?target=fict" rel="nofollow"><img src="/img/sponsor/logo_fict_micro.jpg.pagespeed.ce.yEain7cY8r.jpg" style="border:0px" alt="FICT"/></a>
&nbsp;<a href="/redirect.phtml?target=uisp" rel="nofollow"><img src="/img/sponsor/logo_uisp_micro.jpg.pagespeed.ce.TqlS86I2Jb.jpg" style="border:0px" alt="UISP"/></a>
</p>
</div>
</div> <!-- fine div "container" -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">_uacct="UA-666569-2";urchinTracker();</script>
</body>
</html>
